import type { Chapter } from '../src/shared/lessons.js'
const chapter: Chapter = {
  id: 2, title: 'テーブル設計DDL', summary: '正規化した7枚の表を、制約つきで CREATE TABLE していきます。',
  steps: [
    { id: 'ch02-01', title: '1枚に全部詰めると破綻する', session: 'A',
      connect: { A: { user: 'admin', password: '', database: 'library' } },
      story: '着任初週のミーティングです。総務課からもらった書籍管理の表計算シートを「このまま1枚の表にしてください」と提案されました。本当にそれで大丈夫か、まずは危険性を自分の目で確かめます。',
      explanation: '## 非正規化の表が抱える3つの事故\nシートを1つの表 `books_bad` にそのまま写すと、例えばこうなります。\n\n| book_id | title | author_name | author_birth_year | category_name | copy_count |\n|---|---|---|---|---|---|\n| 1 | データベース設計の実際 | 佐藤花子 | 1985 | 技術 | 3 |\n| 2 | SQL入門 | 佐藤花子 | 1985 | 技術 | 2 |\n| 3 | 図書館の歴史 | 山田一郎 | 1962 | 歴史 | 1 |\n\nこの形には3つの事故が潜みます。\n1. **更新の異常**: 佐藤花子さんの生年が訂正されたら2行を同時に直す必要があります。1行だけ直すと表の中で矛盾します。\n2. **挿入の異常**: 新しい分類「芸術」は、まだ本が1冊もないので登録できません（本の情報がないと行が作れない）。\n3. **削除の異常**: 技術の本を消していくと、最後の1冊を消した時点で「技術」という分類そのものが消えます。\n\n## 正規化とは\n同じ情報は1か所にだけ置き、**ID で参照する**形に組み替えることです。この道場では7枚に分解します。\n- categories（分類）／ authors（著者）／ books（書誌）／ book_authors（書籍と著者の関連）\n- copies（蔵書＝物理的な1冊）／ members（会員）／ loans（貸出）\n\n「1冊の本（書誌）」と「棚にある1冊（蔵書）」が別々なのが図書館ドメインの肝です。同じ本を3冊購入しても書誌は1行のまま、蔵書だけ3行増えます。\n\n## 安全に実験する\n模範解答は BEGIN 〜 ROLLBACK で囲んであるので、実行してもデータベースには何も残りません（PostgreSQL は表の作成もトランザクションで取り消せます。詳細はこの章の最後のステップで扱います）。エディターで実行して、author_name の重複を目で確認してみてください。',
      task: '説明を読み、模範解答をエディターで実行して重複を確認したら「読ました・次へ進む準備」を押してください。何も残らないので採点は不要です。',
      hints: [],
      solution: `BEGIN;
CREATE TABLE public.books_bad (
  book_id integer PRIMARY KEY,
  title text,
  author_name text,
  author_birth_year integer,
  category_name text,
  copy_count integer
);
INSERT INTO public.books_bad VALUES
  (1, 'データベース設計の実際', '佐藤花子', 1985, '技術', 3),
  (2, 'SQL入門', '佐藤花子', 1985, '技術', 2),
  (3, '図書館の歴史', '山田一郎', 1962, '歴史', 1);
SELECT book_id, title, author_name, author_birth_year, category_name FROM public.books_bad ORDER BY book_id;
ROLLBACK;`,
      replay: '',
      check: { type: 'manual' },
      mysqlNote: '正規化の考え方は MySQL でも全く同じです。差が出るのは制約の信頼性で、MySQL 8.0.16 未満は CHECK 制約を書けても無視します（この章の各ステップで都度比較します）。' },
    { id: 'ch02-02', title: 'categories — 自動採番と主キー', session: 'A',
      story: '設計方針が通りました。まずは最小の表で、CREATE TABLE の文法と「自動採番」を身につけます。書架の分類表から作りましょう。',
      explanation: '## CREATE TABLE の読み方\n```sql\nCREATE TABLE public.categories (\n  category_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT categories_pkey PRIMARY KEY,\n  name text CONSTRAINT categories_name_nn NOT NULL CONSTRAINT categories_name_key UNIQUE\n);\n```\n- `integer GENERATED BY DEFAULT AS IDENTITY` — ID 列。行を登録すると自動で連番が振られます（内部的にはシーケンスという採番機が使われます）。`BY DEFAULT` は「明示的に ID を指定すればそれを採用」の意味で、初期データ投入（3章）で役立ちます。\n- `CONSTRAINT categories_pkey PRIMARY KEY` — 主キー。行の身分証で、重複も NULL も許しません。自動的に一意インデックスが作られます。\n- `CONSTRAINT categories_name_nn NOT NULL` — 名前付きの NOT NULL。PostgreSQL 17 から名前が付けられます。エラーの原因箇所が制約名で分かるため、実務の障害対応が早くなる小さく効く工夫です。\n- `CONSTRAINT categories_name_key UNIQUE` — 一意制約。分類名が重複すると棚分けが破綻します。主キーと違い、表に複数置ける点が違います。\n- `text` — PostgreSQL の可変長文字列は長さ無制限の text が既定の選択肢です（MySQL の VARCHAR と違い長さ指定が不要。長さ上限を課したい場面だけ次の books の isbn のように varchar(n) を使います）。\n\n実務の原則は「アプリで必須入力にする」だけでなく、**データベースが最後の砦になる**よう制約を表に書くことです。アプリのバグや、直接 SQL を流す人間がデータを壊せないようにするためです。',
      task: 'categories 表を作成してください。制約名まで模範解答どおりにします（この名前は3章のエラー体験と、後の章の指紋比較に使われます）。',
      hints: ['CREATE TABLE public.categories ( ... ); の形です。', 'category_id は integer GENERATED BY DEFAULT AS IDENTITY で、CONSTRAINT categories_pkey PRIMARY KEY を付けます。', 'name は text に、NOT NULL を categories_name_nn、UNIQUE を categories_name_key という名前で付けます。'],
      solution: `CREATE TABLE public.categories (
  category_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT categories_pkey PRIMARY KEY,
  name text CONSTRAINT categories_name_nn NOT NULL CONSTRAINT categories_name_key UNIQUE
);`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.categories') IS NOT NULL
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'categories') = 2
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'categories' AND column_name = 'category_id' AND is_identity = 'YES' AND identity_generation = 'BY DEFAULT') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.categories') AND conname = 'categories_pkey' AND contype = 'p') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.categories') AND conname = 'categories_name_key' AND contype = 'u') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.categories') AND conname = 'categories_name_nn' AND contype = 'n') = 1` },
      mysqlNote: 'MySQL なら `category_id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, UNIQUE KEY categories_name_key (name)` と書きます。自動採番は IDENTITY ではなく列修飾子の AUTO_INCREMENT（採番状態は表ごとに管理）。NOT NULL に名前は付けられず、エラーは列単位で表示されます。VARCHAR は長さ指定が必須な点も PostgreSQL の text との違いです（MySQL にも長さ自由な TEXT 型はありますが、既定値や一意インデックスの扱いに差があります）。' },
    { id: 'ch02-03', title: 'authors — NULL と CHECK 制約', session: 'A',
      story: '次は著者表です。資料を調べても生年が分からない著者がいます。「不明」をどう表すか、そして入力ミスをどう防ぐかがテーマです。',
      explanation: '## NULL は「不明」、0 ではない\nbirth_year は `integer` で NULL 許容にします。**NULL は「値が不明・未入力」**を表し、西暦0年生まれという事実とは別物です。実務でも「不明を 0 や空文字で代用する」設計は事故のもと（0 は計算に混ざる）なので、素直に NULL を使います。\n\n## CHECK 制約で業務ルールを守る\n```sql\nCONSTRAINT authors_birth_year_check CHECK (birth_year BETWEEN 1 AND 2100)\n```\nCHECK は「この条件を満たす行だけを受け入れる」制約です。西暦1年や2200年のような入力ミスを、データベースの段階で弾きます。制約に名前を付ける（authors_birth_year_check）と、エラー時に「どのルールに抵触したか」がすぐ分かります。\n\n注意点が1つ。**NULL に対する CHECK は UNKNOWN となり通過します**。つまりこの CHECK は「入力があるなら 1〜2100」だけを守り、「必須」は守りません。必須は NOT NULL の役目です（name 列の authors_name_nn が担当します）。NULL の比較は TRUE/FALSE にならない、という三値論理の最初の実例です。',
      task: 'authors 表を作成してください。name は必須、birth_year は NULL 許容で CHECK 制約（1〜2100）を付けます。',
      hints: ['骨格は ch02-02 と同じ CREATE TABLE ... ( ... ); です。', 'birth_year integer には NOT NULL を付けません。', 'CHECK は表の末尾に CONSTRAINT authors_birth_year_check CHECK (birth_year BETWEEN 1 AND 2100) として付けます。'],
      solution: `CREATE TABLE public.authors (
  author_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT authors_pkey PRIMARY KEY,
  name text CONSTRAINT authors_name_nn NOT NULL,
  birth_year integer,
  CONSTRAINT authors_birth_year_check CHECK (birth_year BETWEEN 1 AND 2100)
);`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.authors') IS NOT NULL
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'authors') = 3
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'authors' AND column_name = 'birth_year' AND is_nullable = 'YES') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.authors') AND conname = 'authors_birth_year_check' AND contype = 'c' AND pg_get_constraintdef(oid) LIKE '%birth_year >= 1%' AND pg_get_constraintdef(oid) LIKE '%birth_year <= 2100%') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.authors') AND conname = 'authors_name_nn' AND contype = 'n') = 1` },
      mysqlNote: 'MySQL は 8.0.16 から CHECK 制約が実効的に機能します（それ以前は書けても**無視される**だけでした。レガシー環境の移行では要注意）。違反時は `ERROR 3819 (HY000)` で報告されます。NULL に対する CHECK が UNKNOWN として通過する挙動は MySQL も同じです。' },
    { id: 'ch02-04', title: 'books — 外部キーと ALTER TABLE', session: 'A',
      story: '中核の書誌表です。ISBN・分類・出版年。ついでに「稼働後に列が増える」という実務の定番も体験しておきましょう。館長からは「価格も載せて」と頼まれたところです。',
      explanation: '## 列の型を選ぶ\n- `isbn varchar(13)` — ISBN-13 は常に13桁。PostgreSQL の text に上限はありませんが、**業務ルールとしての長さ**を課したいときは varchar(n) を使います。14桁の入力は 22001 エラーで弾かれます。\n- `title text` — 上限を設けない列は text にします。\n- `category_id integer` + 外部キー — 分類名をここに複製せず、categories への**ID 参照**だけを持ちます（ステップ01の正規化そのものです）。\n- `price numeric(10,2)` — 金額は固定小数点の numeric。float は2進数で表せない小数の誤差が出るので金額には使えません。全体10桁・小数2桁です。\n\n## 外部キーと ON DELETE\n```sql\nCONSTRAINT books_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(category_id) ON DELETE RESTRICT\n```\n存在しない分類 ID で本を登録しようとすると `23503` エラーになります。`ON DELETE RESTRICT` は「本がいる分類は削除禁止」。分類を消すと本が行き場を失うのを防ぎます。\n\n| 選択肢 | 挙動 |\n|---|---|\n| RESTRICT / NO ACTION | 参照されている側の削除を拒否（実務の既定候補） |\n| CASCADE | 参照元の行も一緒に消す（影響が連鎖するので要審査） |\n| SET NULL / SET DEFAULT | 参照元の列を NULL / 既定値にする |\n\n## 後から列を足す（ALTER TABLE）\nシステムは稼働後に「新しい列を足したい」と言われます。そこで books は price 抜きで作り、ALTER TABLE で追加します。\n```sql\nALTER TABLE public.books ADD COLUMN price numeric(10,2) DEFAULT 0 CONSTRAINT books_price_nn NOT NULL;\nALTER TABLE public.books ADD CONSTRAINT books_price_check CHECK (price >= 0);\n```\nPostgreSQL 11 以降、DEFAULT 付きの列追加は既存行の書き換えなしで一瞬で終わります（大きい表でも安心）。CHECK の追加も ALTER TABLE ... ADD CONSTRAINT で後付けできます。',
      task: 'books を price なしで作成し、その後 ALTER TABLE で price（numeric(10,2)・既定0・NOT NULL・0以上のCHECK）を追加してください。',
      hints: ['CREATE TABLE には book_id / isbn / title / category_id / published_year と2つの制約を書きます。', 'isbn は varchar(13) で NOT NULL と UNIQUE（books_isbn_nn / books_isbn_key）。', 'price は ALTER TABLE public.books ADD COLUMN price numeric(10,2) DEFAULT 0 CONSTRAINT books_price_nn NOT NULL; で足します。'],
      solution: `CREATE TABLE public.books (
  book_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT books_pkey PRIMARY KEY,
  isbn varchar(13) CONSTRAINT books_isbn_nn NOT NULL CONSTRAINT books_isbn_key UNIQUE,
  title text CONSTRAINT books_title_nn NOT NULL,
  category_id integer CONSTRAINT books_category_id_nn NOT NULL,
  published_year integer,
  CONSTRAINT books_year_check CHECK (published_year BETWEEN 1 AND 2100),
  CONSTRAINT books_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(category_id) ON DELETE RESTRICT
);
ALTER TABLE public.books ADD COLUMN price numeric(10,2) DEFAULT 0 CONSTRAINT books_price_nn NOT NULL;
ALTER TABLE public.books ADD CONSTRAINT books_price_check CHECK (price >= 0);`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.books') IS NOT NULL
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'books') = 6
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'books' AND column_name = 'isbn' AND character_maximum_length = 13) = 1
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'books' AND column_name = 'price' AND numeric_precision = 10 AND numeric_scale = 2 AND column_default = '0' AND is_nullable = 'NO') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.books') AND contype = 'f' AND pg_get_constraintdef(oid) LIKE '%ON DELETE RESTRICT%') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.books') AND conname IN ('books_year_check', 'books_price_check') AND contype = 'c') = 2
  AND (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'books' AND indexname = 'books_isbn_key') = 1` },
      mysqlNote: 'MySQL でも `ALTER TABLE books ADD COLUMN price DECIMAL(10,2) NOT NULL DEFAULT 0;` と書けます。MySQL 8.0 は ALGORITHM=INSTANT で多くの ADD COLUMN を一瞬で終わらせますが、対応しない操作（列の順序指定など）は表の作り直しが必要です。DECIMAL(10,2)・VARCHAR(13)・ON DELETE の選択肢は MySQL もほぼ同じです（外部キーは InnoDB でのみ機能）。PostgreSQL は DDL の多くをトランザクション内で実行・取り消しできる点が大きく違います（この章の最後のステップで扱います）。' },
    { id: 'ch02-05', title: 'book_authors — 複合主キーと多対多', session: 'A',
      story: '書誌を調べていたら共著が判明しました。1冊の本に複数人の著者がいて、1人の著者が複数冊書いている。「多対多」の関係を表で表します。',
      explanation: '## 多対多は「関連だけの表」で表す\nbooks に著者列を作ると共著が書けず、かといって著者ごとに行を複製するとステップ01の正規化が崩れます。そこで**2つの ID の組だけ**を保存する book_authors を挟みます。\n\n- `CONSTRAINT book_authors_pkey PRIMARY KEY (book_id, author_id)` — **複合主キー**。「同じ本 × 同じ著者の組は1度まで」を、表の構造そのものが保証します。純粋な関連表に連番 ID 列を足す意味は薄く、実務でも複合主キーがよく使われます。\n- books への FK は `ON DELETE CASCADE` — 本を削除したら関連行は意味を失うので一緒に消します。**消えるのは「関連」だけで、著者は消えません**。\n- authors への FK は `ON DELETE RESTRICT` — 著者を消すと関連が黙って消えるのは危険なので、書籍が関連している著者は削除不可にします。\n\nCASCADE と RESTRICT の使い分けは、実務の設計レビューで最も議論になる点です。基準は「その行が消えたとき、意味を失うものは CASCADE、意味が残るものは RESTRICT」です。',
      task: 'book_authors 表を作成してください。2つの外部キーには異なる ON DELETE を付けます。',
      hints: ['book_authors に ID 列は作りません。book_id と author_id の2列だけです。', '主キーは CONSTRAINT book_authors_pkey PRIMARY KEY (book_id, author_id)。', 'books へは ON DELETE CASCADE、authors へは ON DELETE RESTRICT です。'],
      solution: `CREATE TABLE public.book_authors (
  book_id integer CONSTRAINT book_authors_book_id_nn NOT NULL,
  author_id integer CONSTRAINT book_authors_author_id_nn NOT NULL,
  CONSTRAINT book_authors_pkey PRIMARY KEY (book_id, author_id),
  CONSTRAINT book_authors_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.books(book_id) ON DELETE CASCADE,
  CONSTRAINT book_authors_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.authors(author_id) ON DELETE RESTRICT
);`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.book_authors') IS NOT NULL
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'book_authors') = 2
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.book_authors') AND conname = 'book_authors_pkey' AND pg_get_constraintdef(oid) = 'PRIMARY KEY (book_id, author_id)') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.book_authors') AND contype = 'f' AND pg_get_constraintdef(oid) LIKE '%ON DELETE CASCADE%') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.book_authors') AND contype = 'f' AND pg_get_constraintdef(oid) LIKE '%ON DELETE RESTRICT%') = 1` },
      mysqlNote: '複合主キーは MySQL でも `PRIMARY KEY (book_id, author_id)` と同じ書き方です。MySQL の外部キーは参照元にインデックスが必要ですが、複合主キーの先頭列が book_id なので自動的に満たされます。CASCADE/RESTRICT の選択肢と意味も PostgreSQL と同じです。' },
    { id: 'ch02-06', title: 'copies — 物理的な1冊を管理する', session: 'A',
      story: '書誌が決まったので、棚に並ぶ「1冊1冊」を管理します。同じ『SQL入門』が3冊あるとき、貸出の対象はこの中のどれか1冊です。',
      explanation: '## books と copies を分ける理由\nbooks は「タイトルなどの書誌事実」、copies は「図書館が保有する物理的な1冊」です。同じ本を3冊購入しても books は1行のまま、copies が3行増えます。貸出（この章の最後）は必ず copies を対象にします。\n\n- `barcode text ... UNIQUE` — 蔵書にはバーコードの管理ラベルを貼ります。ラベルは1冊に1つなので一意制約です。\n- `acquired_on date DEFAULT CURRENT_DATE` — 「いつ取得したか」。ほとんどは登録した日なので、入力を省略したら今日になるよう既定値を設定します。DEFAULT は INSERT で列を省略したときの値です。\n- `status text DEFAULT \'available\'` + `CHECK (status IN (...))` — 在庫／貸出中／修繕中／紛失の4状態。固定値は text + CHECK で持つのが PostgreSQL の定番です。ENUM 型もありますが、値の追加・変更が利きにくく、実務では text + CHECK が好まれます。\n- books への FK は RESTRICT — 蔵書が残っている書誌は消せません。',
      task: 'copies 表を作成してください。既定値つきの列が2つあります。',
      hints: ['列は copy_id / book_id / barcode / acquired_on / status の5つです。', 'acquired_on は date DEFAULT CURRENT_DATE で NOT NULL、status は text DEFAULT \'available\' です。', 'CHECK (status IN (\'available\', \'loaned\', \'repair\', \'lost\')) を copies_status_check という名前で。'],
      solution: `CREATE TABLE public.copies (
  copy_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT copies_pkey PRIMARY KEY,
  book_id integer CONSTRAINT copies_book_id_nn NOT NULL,
  barcode text CONSTRAINT copies_barcode_nn NOT NULL CONSTRAINT copies_barcode_key UNIQUE,
  acquired_on date DEFAULT CURRENT_DATE CONSTRAINT copies_acquired_on_nn NOT NULL,
  status text DEFAULT 'available' CONSTRAINT copies_status_nn NOT NULL,
  CONSTRAINT copies_status_check CHECK (status IN ('available', 'loaned', 'repair', 'lost')),
  CONSTRAINT copies_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.books(book_id) ON DELETE RESTRICT
);`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.copies') IS NOT NULL
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'copies') = 5
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'copies' AND column_name = 'status' AND column_default = '''available''::text' AND is_nullable = 'NO') = 1
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'copies' AND column_name = 'acquired_on' AND column_default = 'CURRENT_DATE' AND is_nullable = 'NO') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.copies') AND conname = 'copies_status_check' AND contype = 'c') = 1
  AND (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'copies' AND indexname = 'copies_barcode_key') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.copies') AND contype = 'f' AND pg_get_constraintdef(oid) LIKE '%ON DELETE RESTRICT%') = 1` },
      mysqlNote: '固定値の列は MySQL では伝統的に ENUM(\'available\',\'loaned\',...) 型が使われてきました。ただし ENUM は値の追加で ALTER TABLE が必要で、並べ替えも面倒です。MySQL 8.0.16 以降なら PostgreSQL と同じ text + CHECK 構成が使えます。日付の既定値は MySQL でも CURRENT_DATE が使えます（式を既定値にするときは MySQL 8.0.13 以降、`DEFAULT (CURRENT_DATE)` のように括弧が必要です）。' },
    { id: 'ch02-07', title: 'members — NULL 許可の一意制約と退会', session: 'A',
      story: '利用者の登録を受付けます。メールアドレスは任意入力。それから、退会した会員の記録をどう扱うかも決めなければなりません。',
      explanation: '## NULL でも一意制約は働く\n`email text CONSTRAINT members_email_key UNIQUE` — email に NOT NULL を付けていません。メールアドレスを持たない会員がいるからです。ここで便利なのは **UNIQUE でも NULL は複数許される**ことです。「NULL は不明なので、不明どうしは重複とは言えない」という理屈です。実務でよく欲しくなる「無い人は NULL、有る人は必ず一意」がまさにこの挙動です。\n\n- `joined_on date DEFAULT CURRENT_DATE` — 入会日は登録日に。\n- `deleted_at timestamptz` — **退会したら行を消さず、この列に時刻を入れる**運用（ソフト削除）。貸出記録（loans）が会員を参照し続けるので、物理削除は設計上できません。NULL の会員が現役です。\n\n## timestamptz を使う理由\n`timestamptz` はタイムゾーン付きの時刻です。実務では「いつ起きたか」を UTC 換算で保存し、表示側でローカル時刻に直すこの型が推奨されます。夏時間の切替や、別拠点との時刻のすり合わせ事故を防ぎます。',
      task: 'members 表を作成してください。email は NULL 許可の一意制約、deleted_at は NULL 許可の timestamptz です。',
      hints: ['列は member_id / name / email / joined_on / deleted_at の5つです。', 'email は text に CONSTRAINT members_email_key UNIQUE だけ（NOT NULL は付けない）。', 'deleted_at は timestamptz で NOT NULL なしです。'],
      solution: `CREATE TABLE public.members (
  member_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT members_pkey PRIMARY KEY,
  name text CONSTRAINT members_name_nn NOT NULL,
  email text CONSTRAINT members_email_key UNIQUE,
  joined_on date DEFAULT CURRENT_DATE CONSTRAINT members_joined_on_nn NOT NULL,
  deleted_at timestamptz
);`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.members') IS NOT NULL
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'members') = 5
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'members' AND column_name = 'email' AND is_nullable = 'YES') = 1
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'members' AND column_name = 'deleted_at' AND is_nullable = 'YES' AND data_type = 'timestamp with time zone') = 1
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'members' AND column_name = 'joined_on' AND column_default = 'CURRENT_DATE' AND is_nullable = 'NO') = 1
  AND (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'members' AND indexname = 'members_email_key') = 1` },
      mysqlNote: 'MySQL には timestamptz がなく、DATETIME（タイムゾーンなし）か TIMESTAMP（UTC で保存しセッションのタイムゾーンで変換。ただし表せる上限が2038年）を選びます。実務では DATETIME で UTC 運用にするのが安全です。「一意制約で NULL は複数許可される」挙動は MySQL も PostgreSQL と同じです。' },
    { id: 'ch02-08', title: 'loans — 貸出と「1冊1貸出」の保証', session: 'A',
      story: 'いよいよ貸出表です。貸出と返却はこの1枚で記録します。そしてこのシステムで一番大事な業務ルール「同じ蔵書は同時に1件しか貸せない」を、データベース自身に守らせます。',
      explanation: '## 貸出の記録\n- `loaned_on date DEFAULT CURRENT_DATE` と `due_on date NOT NULL` — 貸出日と返却期限。期限がなければ延滞を測れないので必須です。\n- `CHECK (due_on >= loaned_on)` — 貸出日より前の返却期限はあり得ないという業務ルール。\n- `returned_on date` — **NULL = 貸出中**。返却が済んだら日付が入ります。「NULL が未解決を表す」パターンは実務で頻出です。\n- `CHECK (returned_on IS NULL OR returned_on >= loaned_on)` — 返却日は貸出日以降。NULL を通すために OR で書きます。\n- 2つの外部キーは RESTRICT — 貸出の履歴は監査の対象なので、会員や蔵書を削除してまで消せる情報ではありません。\n\n## 1冊1貸出をデータベースで保証する\n「未返却の貸出は、同じ蔵書について高々1行」というルールは、主キーや普通の UNIQUE では表せません（返却済みの過去の貸出は何行あってもよいので）。そこで**部分一意インデックス**を使います。\n```sql\nCREATE UNIQUE INDEX loans_one_open_copy_idx ON public.loans(copy_id) WHERE returned_on IS NULL;\n```\nWHERE つきのインデックスで、「未返却の行だけ」に対して copy_id の一意性を強制します。PostgreSQL に部分一意「制約」はないため、CREATE UNIQUE INDEX で作ります。9章の競合貸出の実験では、このインデックスが同時実行時の最後の砦になります。',
      task: 'loans 表を作成し、未返却貸出に対する部分一意インデックス loans_one_open_copy_idx を作成してください。',
      hints: ['列は loan_id / copy_id / member_id / loaned_on / due_on / returned_on の6つです。', 'CHECK は2つ: due_on >= loaned_on と、returned_on IS NULL OR returned_on >= loaned_on。', "CREATE UNIQUE INDEX loans_one_open_copy_idx ON public.loans(copy_id) WHERE returned_on IS NULL; を最後に。"],
      solution: `CREATE TABLE public.loans (
  loan_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT loans_pkey PRIMARY KEY,
  copy_id integer CONSTRAINT loans_copy_id_nn NOT NULL,
  member_id integer CONSTRAINT loans_member_id_nn NOT NULL,
  loaned_on date DEFAULT CURRENT_DATE CONSTRAINT loans_loaned_on_nn NOT NULL,
  due_on date CONSTRAINT loans_due_on_nn NOT NULL,
  returned_on date,
  CONSTRAINT loans_due_on_check CHECK (due_on >= loaned_on),
  CONSTRAINT loans_returned_on_check CHECK (returned_on IS NULL OR returned_on >= loaned_on),
  CONSTRAINT loans_copy_id_fkey FOREIGN KEY (copy_id) REFERENCES public.copies(copy_id) ON DELETE RESTRICT,
  CONSTRAINT loans_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(member_id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX loans_one_open_copy_idx ON public.loans(copy_id) WHERE returned_on IS NULL;`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.loans') IS NOT NULL
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'loans') = 6
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.loans') AND contype = 'c' AND conname IN ('loans_due_on_check', 'loans_returned_on_check')) = 2
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.loans') AND contype = 'f' AND pg_get_constraintdef(oid) LIKE '%ON DELETE RESTRICT%') = 2
  AND (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'loans' AND indexname = 'loans_one_open_copy_idx' AND indexdef LIKE '%UNIQUE%' AND indexdef LIKE '%WHERE%') = 1` },
      mysqlNote: 'MySQL に部分インデックスはありません。「未返却だけ一意」を表すには、例えば未返却なら 1、返却済みなら NULL を返す生成列 (8.0 の GENERATED COLUMN) を作り `UNIQUE(copy_id, is_open)` とする工夫が必要です（NULL は一意制約に引っかからない性質を利用します）。CHECK と外部キーの基本挙動は MySQL（InnoDB）もほぼ同じです。' },
    { id: 'ch02-09', title: 'COMMENT と安全な DDL 失敗（ROLLBACK）', session: 'A',
      story: '7枚が揃いました。仕上げに、未来の仲間（と半年後の自分）へのメモを表に仕込み、PostgreSQL ならではの「DDL の安全な実験」をします。',
      explanation: '## COMMENT で設計意図を残す\n```sql\nCOMMENT ON TABLE public.books IS \'書誌情報。物理的な一冊は copies で管理する\';\n```\nCOMMENT はカタログに保存され、psql の `\\d+` や各種ツールで見られます。「books に蔵書が入っている」と誤解して copies を作らない事故は、この一文で防げます。列にも `COMMENT ON COLUMN` が使えます。表定義はチームの共有財産なので、実務では必須の作業です。\n\n## DDL はトランザクションできる\nPostgreSQL の CREATE TABLE や ALTER TABLE はトランザクションの中で実行でき、ROLLBACK で取り消せます。次の手順を1回ずつ**別の送信**で試してください（セッションバーの状態が idle → transaction → idle と変わります）。\n\n1. `BEGIN;`\n2. `ALTER TABLE public.books ADD COLUMN trial_memo text;`\n3. `SELECT count(*)::int AS trial FROM information_schema.columns WHERE table_schema = \'public\' AND table_name = \'books\' AND column_name = \'trial_memo\';` → 1 が返る\n4. `ROLLBACK;` → 列定義が消える\n\n**MySQL では DDL が暗黙コミットされる**ので、ここは大きな違いです。マイグレーションが失敗時に自動で元に戻るかどうかに直結します。\n\n模範解答は COMMENT の文だけです。実験は ROLLBACK で消えるので採点には影響しません。実験の後は必ず ROLLBACK で閉じてください。採点は**別の接続からコミット済みの状態**を見るため、開いたままのトランザクションの中で COMMENT を実行しても合格しません（セッションバーの表示が transaction のままなら、まず ROLLBACK です）。',
      task: "books に COMMENT を付けた後、BEGIN 〜 ROLLBACK の中で trial_memo 列を足して消す実験をしてください。採点は「COMMENT が付き、かつ books が6列のまま」であることを見ます。",
      hints: ["COMMENT ON TABLE public.books IS '書誌情報。物理的な一冊は copies で管理する'; です。", '実験は BEGIN と ROLLBACK の間に ALTER TABLE を挟みます。', '実験が終わったら ROLLBACK で閉じます（トランザクションが開いたままだと COMMENT が採点に反映されません）。'],
      solution: `COMMENT ON TABLE public.books IS '書誌情報。物理的な一冊は copies で管理する';`,
      check: { type: 'sql', sql: `SELECT obj_description('public.books'::regclass, 'pg_class') = '書誌情報。物理的な一冊は copies で管理する'
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'books') = 6` },
      mysqlNote: 'MySQL には COMMENT ON 構文がなく、CREATE TABLE の列定義・表定義に `COMMENT \'...\'` を埋め込む方式です（ALTER TABLE で後から追加もできます）。DDL の暗黙コミットについて: MySQL では CREATE TABLE / ALTER TABLE の実行時に、前のトランザクションが暗黙に COMMIT されます。DDL を含む一連の変更をアトミックにできないため、マイグレーションは「適用済みの記録」で冪等性を担保する運用が主流です。' },
  ],
}
export default chapter
