import type { Chapter } from '../src/shared/lessons.js'
const chapter: Chapter = {
  id: 8, title: 'インデックス性能', summary: '百万件の履歴を使い実行計画と索引を学びます。',
  steps: [
    { id: 'ch08-01', title: 'loan_history — 性能実験用の100万行表を作る', session: 'A',
      story: 'システムは順調ですが、館長が「貸出の全履歴を保存して、会員ページからすぐ見えるようにしたい」と言い出しました。履歴は日々増え続ける表の代表です。性能の勉強には、本番で泣かないための「十分に大きい表」が必要です。',
      explanation: '## 性能実験は本物の大きさで\n50行の表で索引の効果を語ることはできません（どうやっても速いから）。この章では **loan_history（貸出履歴）** に100万行を入れ、インデックスの効果を実測します。\n\n```sql\nCREATE TABLE public.loan_history (\n  history_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT loan_history_pkey PRIMARY KEY,\n  member_id integer NOT NULL,\n  book_id integer NOT NULL,\n  loaned_on date NOT NULL,\n  returned_on date,\n  note text NOT NULL DEFAULT \'\'\n);\n```\n- `history_id bigint` — 履歴は整数の上限（約21億）を超えるかもしれない表です。ID には int8 を使うのが実務の作法（integer の自動採番は約21億で枯渇します）。\n- `returned_on date` — NULL = 貸出中、という loans と同じ約束を履歴でも使います。\n- `note text NOT NULL DEFAULT \'\'` — 既定値を「空文字」にすることで NULL と空文字の混在を防ぐ、地味な実務ワザです。\n- この表は**性能実験専用**なので、外部キーや CHECK は付けません（FK の維持コストが実験の邪魔になるため。実務の表は2章のように制約を付けます）。\n\n**なぜ実務でこうするか**: 「履歴」「ログ」「イベント」は書き込み量が多く、表設計のミス（型の選択ミス、不必要な制約や索引）があとで効いてくる表です。性能を見据えた設計は、この章で実測しながら学びます。',
      task: 'loan_history 表を作成してください（contract の列定義どおり。主キー名は loan_history_pkey）。',
      hints: ['CREATE TABLE public.loan_history ( ... ); の形です。', 'history_id は bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT loan_history_pkey PRIMARY KEY です。', 'note は text NOT NULL DEFAULT \'\' 、returned_on は NULL 許容の date です。'],
      solution: `CREATE TABLE public.loan_history (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT loan_history_pkey PRIMARY KEY,
  member_id integer NOT NULL,
  book_id integer NOT NULL,
  loaned_on date NOT NULL,
  returned_on date,
  note text NOT NULL DEFAULT ''
);`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.loan_history') IS NOT NULL
  AND (SELECT c.relkind FROM pg_class c WHERE c.oid = to_regclass('public.loan_history')) = 'r'
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'loan_history') = 6
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'loan_history'
        AND column_name = 'history_id' AND data_type = 'bigint' AND is_identity = 'YES' AND identity_generation = 'BY DEFAULT') = 1
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'loan_history'
        AND column_name = 'note' AND is_nullable = 'NO' AND column_default IS NOT NULL) = 1
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'loan_history'
        AND column_name = 'returned_on' AND is_nullable = 'YES') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = to_regclass('public.loan_history') AND conname = 'loan_history_pkey' AND contype = 'p') = 1` },
      mysqlNote: 'MySQL なら `history_id BIGINT AUTO_INCREMENT PRIMARY KEY` と書きます。MySQL の AUTO_INCREMENT 採番は表ごとに管理され、明示 ID 挿入時に採番位置が自動で進む点が PostgreSQL の IDENTITY（BY DEFAULT）と違います。`text NOT NULL DEFAULT \'\'` は MySQL でもそのまま使えます。' },
    { id: 'ch08-02', title: '100万行を1文で投入する', session: 'A',
      story: '性能実験の準備です。100万行を手で書く人はいません。3章で学んだ INSERT ... SELECT と generate_series で、決定的なデータを一気に作ります。',
      explanation: '## 製造データは「式」で作る\n```sql\nINSERT INTO public.loan_history (history_id, member_id, book_id, loaned_on, returned_on, note)\nSELECT n,\n       (n - 1) % 20 + 1,\n       (n - 1) % 50 + 1,\n       CURRENT_DATE - (n % 730)::integer,\n       CASE WHEN n % 10 = 0 THEN NULL ELSE CURRENT_DATE - (n % 730)::integer + 7 END,\n       \'history \' || n\nFROM generate_series(1, 1000000) AS n;\n```\nこの1文で作られるデータの性質（この章全体で使い続ける重要情報）:\n- **会員は 1〜20 が均等**（各50,000行 = 5%）。`member_id = 7` のような検索は「100万行中5万行」= 低選択度の例になります。\n- **書誌は 1〜50 が均等**（各20,000行）。\n- **貸出日は過去730日（2年）に均等**。1日あたり約1,370行。\n- **10行に1行が貸出中**（n % 10 = 0）= 100,000行。**90% は返却済み**です。\n- ID を明示しているので、最後に `setval` で採番位置を100万に合わせます（3章の seed と同じ作法）。\n\n**なぜ実務でこうするか**: 移行テストや負荷テストのデータは「本番っぽい分布」で作るのがコツです。均等・周期的なこのデータは、索引が効く条件・効かない条件を机上で計算できるので、実験に最適です。実行には数秒かかります。',
      task: '100万行を INSERT ... SELECT で投入し、最後に setval で採番位置を合わせてください。確認のため最後の SELECT で行数を表示します。',
      hints: ['INSERT INTO public.loan_history (history_id, member_id, book_id, loaned_on, returned_on, note) SELECT ... FROM generate_series(1, 1000000) AS n; です。', 'member_id は (n - 1) % 20 + 1、book_id は (n - 1) % 50 + 1、loaned_on は CURRENT_DATE - (n % 730)::integer。returned_on は CASE WHEN n % 10 = 0 THEN NULL ELSE（貸出日 + 7日）です。', '最後に SELECT setval(pg_get_serial_sequence(\'public.loan_history\', \'history_id\'), 1000000, true); を実行します。'],
      solution: `INSERT INTO public.loan_history (history_id, member_id, book_id, loaned_on, returned_on, note)
SELECT n,
       (n - 1) % 20 + 1,
       (n - 1) % 50 + 1,
       CURRENT_DATE - (n % 730)::integer,
       CASE WHEN n % 10 = 0 THEN NULL ELSE CURRENT_DATE - (n % 730)::integer + 7 END,
       'history ' || n
FROM generate_series(1, 1000000) AS n;
SELECT setval(pg_get_serial_sequence('public.loan_history', 'history_id'), 1000000, true);
SELECT count(*)::int AS total_rows FROM public.loan_history;`,
      check: { type: 'sql', sql: `SELECT (SELECT count(*) FROM public.loan_history) = 1000000
  AND (SELECT count(*) FROM public.loan_history WHERE member_id = 1) = 50000
  AND (SELECT count(*) FROM public.loan_history WHERE book_id = 7) = 20000
  AND (SELECT count(*) FROM public.loan_history WHERE returned_on IS NULL) = 100000
  AND (SELECT count(*) FROM public.loan_history WHERE member_id <> (history_id - 1) % 20 + 1) = 0
  AND (SELECT count(*) FROM public.loan_history WHERE book_id <> (history_id - 1) % 50 + 1) = 0
  AND (SELECT count(*) FROM public.loan_history WHERE loaned_on <> CURRENT_DATE - (history_id % 730)::integer) = 0
  AND (SELECT count(*) FROM public.loan_history WHERE returned_on IS DISTINCT FROM
         (CASE WHEN history_id % 10 = 0 THEN NULL ELSE CURRENT_DATE - (history_id % 730)::integer + 7 END)) = 0
  AND (SELECT count(*) FROM public.loan_history WHERE note <> 'history ' || history_id) = 0` },
      mysqlNote: 'MySQL に generate_series はないので、再帰 CTE（`WITH RECURSIVE`）で番号を生成するのが定番です（3章参照）。MySQL の INSERT ... SELECT で100万行を作る方法は同じです。明示 ID 挿入後の採番位置は MySQL では自動で進む（AUTO_INCREMENT の性質）ため、setval 相当の操作は不要な点が PostgreSQL と異なります。' },
    { id: 'ch08-03', title: 'ANALYZE — プランナに「表の中身」を教える', session: 'A',
      story: '100万行が入りました。ところで、PostgreSQL はこの表の「中身」を知っているのでしょうか。問い合わせ計画を立てるプランナの情報源を整えます。',
      explanation: '## プランナは統計情報で動く\nPostgreSQL のプランナ（問い合わせ計画を立てる部品）は、表の中身を全部読んでから計画を立てるわけではありません。**統計情報**（各行の値の分布・重複度・NULL の割合など）を参考に、計画を「見積もり」で組みます。\n\n統計は `ANALYZE` で採取します。\n```sql\nANALYZE public.loan_history;\n```\n実行すると:\n- 表から一定数の行を**サンプリング**して、pg_statistic（見える形は pg_stats ビュー）に保存します\n- `member_id` は「20種類でほぼ均等」「nullfrac = 0」のような要約になります\n- 以降の EXPLAIN の「rows=...」は、この統計から計算されます\n\n100万行を投入した直後のように、**データが大きく変わった後は統計が古くなります**。統計が古いと見積もりが当てにならず、索引があるのに使われない（あるいは逆）という事故につながります。大量データの投入・更新の後は ANALYZE を実行する——VACUUM と並ぶ運用の基本です（autovacuum が autoanalyze として自動で行う場合もあります。後のステップで両方を見ます）。\n\n確認は pg_stats ビューで見られます（例: `SELECT attname, n_distinct FROM pg_stats WHERE tablename = \'loan_history\';`）。\n\n**なぜ実務でこうするか**: バッチで大量投入したのに遅い、は「統計が古い」が定番原因の1つです。「投入 → ANALYZE」をセットにしておくと、深夜バッチ後の朝一が急に遅い、という事態を防げます。',
      task: 'ANALYZE を実行して、loan_history の統計情報を採取してください（pg_stat_user_tables に手動 ANALYZE の記録が残ることを採点します）。',
      hints: ['ANALYZE public.loan_history; を単独の文で実行します。', 'VACUUM と違い、ANALYZE は統計採取だけが仕事です（不要な領域の回収はしません）。', '実行後の統計は pg_stats ビューで確認できます。'],
      solution: `ANALYZE public.loan_history;
SELECT attname, n_distinct, null_frac FROM pg_stats WHERE schemaname = 'public' AND tablename = 'loan_history' ORDER BY attname;`,
      check: { type: 'sql', sql: `SELECT (SELECT count(*) FROM pg_stat_user_tables
         WHERE schemaname = 'public' AND relname = 'loan_history' AND last_analyze IS NOT NULL) = 1` },
      mysqlNote: 'MySQL の対応は `ANALYZE TABLE loan_history;` です（InnoDB の統計を更新）。MySQL 8.0 は統計をテーブルに**永続化**（innodb_stats_persistent）し、自動更新のタイミング（変更行数の閾値 innodb_stats_auto_recalc）を設定できます。「統計を更新する」という発想自体は PostgreSQL と共通です。' },
    { id: 'ch08-04', title: 'EXPLAIN — 実行計画の読み方と「実際」の見方', session: 'A',
      story: '索引を作る前に、**読めないと直せない**ものを身につけます。実行計画です。PostgreSQL は自分がどう問い合わせを実行するか説明できる、珍しい誠実なデータベースです。',
      explanation: '## EXPLAIN と EXPLAIN ANALYZE\n```sql\n-- 見積もりだけを見る（実行はしない）\nEXPLAIN SELECT * FROM public.loan_history WHERE member_id = 7;\n\n-- 実際に実行して、実測も見る\nEXPLAIN ANALYZE SELECT * FROM public.loan_history WHERE member_id = 7;\n```\nEXPLAIN の出力は**木構造**で、字下げが「親子」を表します（子が先に実行される）。まだ索引の無い今、この問い合わせはこう動きます:\n\n```\nGather  (cost=1000.00..19372.33 rows=48300 width=38)\n  Workers Planned: 2\n  ->  Parallel Seq Scan on loan_history  (cost=0.00..13542.33 rows=20125 width=38)\n        Filter: (member_id = 7)\n```\n読み方の語彙:\n- **Seq Scan（全件走査）** — 表を先頭から全部読む。行数が多いと遅いが、多くの行が必要なら最善でもある\n- **Parallel Seq Scan / Gather** — 助っ人（ワーカー）で並行に全件走査し、結果を集約。大表の定番\n- **cost=起動コスト..合計コスト** — コストは「ページ読み込みの回数」を基準にした**無単位の見積もり**。速さの予測に使う相対値で、ミリ秒ではありません\n- **rows=48300** — 見積もり行数（統計から計算）。実際は50,000行なので、かなりの精度です\n- **width=38** — 1行あたりの平均バイト数の見積もり\n- **Filter** — 読んだ行に適用する絞り込み。**Rows Removed by Filter**（EXPLAIN ANALYZE の表示）は「読んだが捨てた行数」——この数字が巨大なら「索引が必要」のサインです\n\nEXPLAIN ANALYZE が付け足す「実際」:\n- `(actual time=開始..終了 行数 loops=回数)` — 実測時間（ミリ秒）と実際の行数\n- 並行実行の集計は「1ワーカーあたりの平均 × loops」なので、rows=16666.67 loops=3 のように小数が出ます\n- 末尾の **Planning Time / Execution Time** — 計画を立てた時間と実行した時間の合計\n- ミリ秒単位で表示される actual time は環境によって毎回変わります。**比べるべきは構造（Scan の種類・行数）であって、タイムは目安**です\n\n※ EXPLAIN は実行しませんが、**EXPLAIN ANALYZE は本当に実行します**。UPDATE や DELETE に使う場合は9章の ROLLBACK の知識と組み合わせます。\n\n**なぜ実務でこうするか**: 「遅い SQL」の相談で最初に見るのが EXPLAIN です。見積もり（rows）と実測（actual rows）が大きくズレているなら統計情報の問題、Rows Removed by Filter が巨大なら索引の問題、と原因の切り分けが一発でできます。',
      task: '模範解答の2文を実行して、EXPLAIN と EXPLAIN ANALYZE の出力を見比べてください。読めたら「読ました・次へ進む準備」を押します。',
      hints: ['1つ目は見積もり、2つ目は実測つきの計画です。', 'actual time・Rows Removed by Filter・Execution Time が EXPLAIN ANALYZE だけに現れる行です。', '行を減らすために LIMIT を付けるのは計画測定の基本ですが、ここでは全件のまま見ます。'],
      solution: `EXPLAIN SELECT * FROM public.loan_history WHERE member_id = 7;
EXPLAIN ANALYZE SELECT * FROM public.loan_history WHERE member_id = 7;`,
      replay: '',
      check: { type: 'manual' },
      mysqlNote: 'MySQL は `EXPLAIN`（表形式: type=ALL が全件走査、key=使う索引、rows=見積行数、Extra=Using where 等）と `EXPLAIN ANALYZE`（8.0.18以降、実際の時間つき）を持ちます。PostgreSQL は木構造・JSON・text で同じ情報を出しますが、**並列実行の可視化（Workers Launched）や BUFFERS（読んだページ数）** は PostgreSQL の EXPLAIN ANALYZE の方が詳しいです。MySQL では Handler_read_% ステータス変数で読み方の実態を探ります。' },
    { id: 'ch08-05', title: 'B-tree 索引 — member_id の検索が変わる瞬間', session: 'A',
      story: '会員ページで「この会員の貸出履歴」を表示する場面を思い浮かべてください。100万行の表から、特定の会員（約5万行）だけを取り出す問い合わせです。最初の索引を作ります。',
      explanation: '## 索引（インデックス）は「目次」\n```sql\nCREATE INDEX loan_history_member_idx ON public.loan_history (member_id);\n```\nデフォルトの索引方式は **B-tree**（平衡木）です。列の値でソートされた木構造で、目的の値を「ページ読み込み数回のたどり」で見つけられます。2章の主キーや一意制約も、内部では B-tree 索引で実装されています。\n\n**索引を作る前後で、同じ問い合わせの計画を見比べます。**（模範解答を1回送ると、作成前 → 作成 → 作成後が並んで表示されます）\n\n作成前:\n```\nGather  (cost=1000.00..19372.33 ...)\n  ->  Parallel Seq Scan on loan_history\n        Filter: (member_id = 7)\n```\n作成後:\n```\nBitmap Heap Scan on loan_history  (cost=560.44..9520.28 rows=50067 ...)\n  Recheck Cond: (member_id = 7)\n  ->  Bitmap Index Scan on loan_history_member_idx\n        Index Cond: (member_id = 7)\n```\n- **Bitmap Index Scan** — 索引で該当行の「位置」を集め（ビットマップ）、それから表を一気に読む。中間量（5万行 = 表の5%）を取るときの定番\n- **Index Scan** — 索引をたどりながら1行ずつ表へ。もっと少数（0.1%以下）のときに選ばれます\n- コストの見積もりが **約19,000 → 約9,500** に半減。実際の実行時間も短くなります（EXPLAIN ANALYZE で確認できます）\n\n索引を作っただけではクエリは速くなりません。**プランナが「使う価値がある」と判断して初めて**計画が変わります。だからこそ統計情報（前のステップの ANALYZE）が重要です。\n\n**なぜ実務でこうするか**: この索引は「member_id で始まる検索」を全部カバーします。WHERE の形に合わせて索引を設計し、EXPLAIN で本当に使われているかを**確認して終わる**——索引チューニングの基本サイクルです（使われない索引は維持コストだけを生む、と10章のあとで見ます）。',
      task: 'EXPLAIN（索引なし）→ CREATE INDEX loan_history_member_idx → EXPLAIN（索引あり）を1回の送信で実行してください。計画が Seq Scan から Bitmap Heap Scan に変わることを採点は索引の存在で確認します。',
      hints: ['最初の EXPLAIN (COSTS OFF) SELECT * FROM public.loan_history WHERE member_id = 7; で「前」の計画を取ります。', 'CREATE INDEX loan_history_member_idx ON public.loan_history (member_id); が本体です（USING btree が既定）。', '最後にもう一度同じ EXPLAIN を実行して計画の変化を見ます。'],
      solution: `EXPLAIN (COSTS OFF) SELECT * FROM public.loan_history WHERE member_id = 7;
CREATE INDEX loan_history_member_idx ON public.loan_history (member_id);
EXPLAIN (COSTS OFF) SELECT * FROM public.loan_history WHERE member_id = 7;`,
      check: { type: 'sql', sql: `SELECT (SELECT count(*) FROM pg_indexes
         WHERE schemaname = 'public' AND tablename = 'loan_history'
           AND indexname = 'loan_history_member_idx' AND indexdef LIKE '%(member_id)%') = 1` },
      mysqlNote: 'MySQL（InnoDB）の索引も B+Tree です。大きな違いは**表そのものが主キーの B+Tree**（クラスタ索引）で、追加の索引の葉に主キー値を持つ点です（PostgreSQL は表と索引が独立・ヒープ）。そのため MySQL では「できるだけ主キーで突く」「複合索引の後続列でカバーする」設計が効きやすくなります。索引の作り方 `CREATE INDEX ... ON t (col)` は両方同じです。' },
    { id: 'ch08-06', title: '複合索引 — 列の並び順が使い方を決める', session: 'A',
      story: '会員ページの次は「この会員の最近の貸出」。member_id と日付の**組み合わせ**で検索します。1列の索引に不満が出てきたとき、複合索引の出番です。',
      explanation: '## 複合索引は「左から一致」で効く\n```sql\nCREATE INDEX loan_history_member_date_idx ON public.loan_history (member_id, loaned_on);\n```\n複合索引は (member_id, loaned_on) の**組**でソートされます。電話帳が「姓・名」で並んでいるのと同じで、\n- `member_id = 7` … ○ 使える（先頭列で探せる）\n- `member_id = 7 AND loaned_on >= ...` … ◎ **最高に使える**（先頭列で絞って、2列目でさらに詰める）\n- `loaned_on = ...` だけ … △ **左端が無いと「探しに」は行けない**\n\n模範解答で3つの EXPLAIN を順に見比べてください。\n\n1. `member_id = 7 AND loaned_on >= CURRENT_DATE - 7`（索引作成前）… member_idx の Bitmap に絞り込みの Filter が乗る（cost 約9800）\n2. 同じ問い合わせ（索引作成後）… **2列とも Index Cond に入る**（cost 約1700。685行を直接当てる）\n3. `loaned_on = CURRENT_DATE - 10`（索引作成後）… 驚くことに composite 索引が使われますが、Index Cond は loaned_on だけ。**索引全体を総なめして**該当を拾っています（cost 約3700）。使える、と効率的、は別物です\n\n**列順の選び方**（実務の判断基準）:\n- **等価条件でよく使う列を左に**、範囲条件の列を右に\n- 先頭列だけで検索する用途があるなら、1列索引 (member_id) も残しておく価値がある——この教材の契約でも両方残します\n- 並び順が違うだけで「使えるクエリの形」が変わるので、**アプリの WHERE を読んでから作る**のが鉄則です\n\n**なぜ実務でこうするか**: 複合索引1本で複数のクエリを賄える一方で、列順を間違えると誰も使わない重い索引になります。pg_stat_user_indexes の idx_scan で「実際に使われた回数」を見て、使われない索引は落とす——これが索引の保守運用です。',
      task: 'EXPLAIN（複合索引なし）→ CREATE INDEX loan_history_member_date_idx (member_id, loaned_on) → EXPLAIN（あり・member+日付）→ EXPLAIN（あり・日付だけ）を実行してください。',
      hints: ['CREATE INDEX loan_history_member_date_idx ON public.loan_history (member_id, loaned_on); です（列の並び順が肝心）。', 'member_id = 7 AND loaned_on >= CURRENT_DATE - 7 が複合索引が本領を発揮する問い合わせです。', 'loaned_on = CURRENT_DATE - 10 の計画で、Index Cond が loaned_on だけになっていることを確認します。'],
      solution: `EXPLAIN SELECT * FROM public.loan_history WHERE member_id = 7 AND loaned_on >= CURRENT_DATE - 7;
CREATE INDEX loan_history_member_date_idx ON public.loan_history (member_id, loaned_on);
EXPLAIN SELECT * FROM public.loan_history WHERE member_id = 7 AND loaned_on >= CURRENT_DATE - 7;
EXPLAIN SELECT * FROM public.loan_history WHERE loaned_on = CURRENT_DATE - 10;`,
      check: { type: 'sql', sql: `SELECT (SELECT count(*) FROM pg_indexes
         WHERE schemaname = 'public' AND tablename = 'loan_history'
           AND indexname = 'loan_history_member_date_idx' AND indexdef LIKE '%(member_id, loaned_on)%') = 1` },
      mysqlNote: 'MySQL の複合索引も「左端の原則（leftmost prefix）」で動きます（MySQL の用語でも leftmost）。MySQL の EXPLAIN では possible_keys / key に候補と採用された索引が出るので、同じ確認ができます。MySQL には索引ヒント（FORCE INDEX 等）がありますが、「ヒントで無理やり使わせる」のは最終手段なのは PostgreSQL でも同じです。' },
    { id: 'ch08-07', title: '部分索引 — 貸出中の100,000行だけに索引を作る', session: 'A',
      story: '履歴の90%は返却済みです。でも「現在貸出中」だけが業務の関心ごと。表全体に索引を作るのは、9割のどうでもいい行にまでコストを払うことになりませんか。',
      explanation: '## WHERE つきの索引\n```sql\nCREATE INDEX loan_history_open_idx ON public.loan_history (loaned_on) WHERE returned_on IS NULL;\n```\n`WHERE` を付けた索引（**部分索引 / Partial Index**）は、**条件に合う行だけ**を索引に入れます。\n- 表全体: 1,000,000行。貸出中: 100,000行（10%）\n- 実測でも、索引の大きさは **約6.8MB（複合索引）に対して約0.7MB**。1/10 以下です（模範解答の SELECT pg_relation_size で確認できます）\n\n**クエリ側の条件と完全に一致させる必要があります。** `WHERE returned_on IS NULL AND loaned_on = ...` の形の問い合わせだけがこの索引を使えます。部分索引の条件が含まれない検索（返却済みも見る集計など）は、この索引を一切見ません。\n\n見積もりと実測の面白い話も見られます。このデータでは「n%730=10 の行は必ず n%10=0（＝貸出中）」という**相関**がありますが、統計情報は列ごとに独立だと仮定するので、見積もりは約140行・実際は1370行と**大きくズレます**。列間の相関を統計は捉えられない——見積もりと実測を見比べる理由そのものです。\n\n**なぜ実務でこうするか**: 「未返却だけ」「未処理だけ」「最近30日だけ」のように、業務上よく検索する部分が表のごく一部を占めるケースは非常に多いです。部分索引はその部分だけに索引のコスト（容量と書き込み時の維持費）を集中できます。2章で作った loans_one_open_copy_idx（未返却だけの一意索引）もこの方式です。',
      task: 'EXPLAIN（部分索引なし）→ CREATE INDEX loan_history_open_idx（loaned_on に WHERE returned_on IS NULL）→ EXPLAIN（あり）と、索引サイズの比較を1回の送信で実行してください。',
      hints: ['CREATE INDEX loan_history_open_idx ON public.loan_history (loaned_on) WHERE returned_on IS NULL; です。', '見比べる問い合わせは SELECT * FROM public.loan_history WHERE returned_on IS NULL AND loaned_on = CURRENT_DATE - 10; です。', '最後の SELECT で pg_relation_size を使って複合索引と部分索引の大きさを比べます。'],
      solution: `EXPLAIN SELECT * FROM public.loan_history WHERE returned_on IS NULL AND loaned_on = CURRENT_DATE - 10;
CREATE INDEX loan_history_open_idx ON public.loan_history (loaned_on) WHERE returned_on IS NULL;
EXPLAIN SELECT * FROM public.loan_history WHERE returned_on IS NULL AND loaned_on = CURRENT_DATE - 10;
SELECT indexname, pg_size_pretty(pg_relation_size('public.' || indexname)) AS size
FROM pg_indexes
WHERE schemaname = 'public' AND tablename = 'loan_history'
  AND indexname IN ('loan_history_member_date_idx', 'loan_history_open_idx')
ORDER BY indexname;`,
      check: { type: 'sql', sql: `SELECT (SELECT count(*) FROM pg_indexes
         WHERE schemaname = 'public' AND tablename = 'loan_history'
           AND indexname = 'loan_history_open_idx' AND indexdef LIKE '%(loaned_on) WHERE (returned_on IS NULL)%') = 1
  AND (SELECT pg_relation_size('public.loan_history_open_idx'::regclass)
         < pg_relation_size('public.loan_history_member_date_idx'::regclass))` },
      mysqlNote: '**MySQL には部分索引がありません**（8.0時点）。実務の代替策は2つ: (1) 生成列（GENERATED COLUMN）で returned_on IS NULL を 0/1 の列にして複合索引に入れる、(2) 「貸出中だけを別表に入れる」（PostgreSQL なら部分索引で済む設計を、MySQL では表分割で実現する）。PostgreSQL の部分索引を移植するときは、この表分割が現実的な選択肢になります。' },
    { id: 'ch08-08', title: '式索引 — lower(title) をそのまま索引にする', session: 'A',
      story: '司書から「検索窓に書名を小文字で入れたら引っかかるようにしたい」と要望が来ました。`WHERE lower(title) = ...` という問い合わせは、title に作った普通の索引を使えません。索引の方を式に合わせるのです。',
      explanation: '## 列を加工する検索には「式索引」\n```sql\nCREATE INDEX books_title_lower_idx ON public.books (lower(title));\n```\n索引に入れるのは「列の値」ではなく**式の結果**（lower(title)）です。すると `WHERE lower(title) = \'...\'` が索引で探せるようになります。\n\n大事な対応関係:\n- `WHERE lower(title) = ...` に答えられるのは **lower(title) の索引** だけ\n- title に普通の索引を作っても、この問い合わせには**使えない**（式が噛み合わないから）\n- **索引側と検索側の式が文字どおり一致している**ことが条件です（次のステップで「不一致」の例を見ます）\n\n## 小さい表では全件走査が「正解」になる\nbooks は50行しかないので、索引を作っても計画は Seq Scan のままかもしれません。これは**バグではなくプランナの正しい判断**です（50行全部読む方が、索引を経由するより速い）。\n\n索引が「使える」という事実だけは、実験用スイッチで確認できます。\n```sql\nSET enable_seqscan = off;   -- 実験専用: 全件走査を使わないで組んでみる\nEXPLAIN (COSTS OFF) SELECT * FROM public.books WHERE lower(title) = \'図書館の本07\';\nRESET enable_seqscan;      -- 必ず戻す\n```\n`Index Scan using books_title_lower_idx ... Index Cond: (lower(title) = ...)` が見られれば、索引は正しく使える状態です。表が大きくなれば、この計画はスイッチなしで選ばれるようになります。\n\n**なぜ実務でこうするか**: 大文字小文字を無視した検索・メールアドレスの正規化検索・日付の年月検索など、「正規化した形で探す」要件は頻出です。アプリ側で「lower() した列」を別に持つ（非正規化）前に、式索引で済むか検討するのが筋の良い順番です。',
      task: 'EXPLAIN（索引なし）→ CREATE INDEX books_title_lower_idx (lower(title)) → SET enable_seqscan = off で EXPLAIN（索引あり）→ RESET。1回の送信で実行してください。',
      hints: ['CREATE INDEX books_title_lower_idx ON public.books (lower(title)); です（列名ではなく式を括弧に入れる）。', '見る問い合わせは SELECT * FROM public.books WHERE lower(title) = \'図書館の本07\'; です。', 'SET enable_seqscan = off; のあとの EXPLAIN で Index Scan が見えたら、最後に RESET enable_seqscan; で戻します。'],
      solution: `EXPLAIN (COSTS OFF) SELECT * FROM public.books WHERE lower(title) = '図書館の本07';
CREATE INDEX books_title_lower_idx ON public.books (lower(title));
SET enable_seqscan = off;
EXPLAIN (COSTS OFF) SELECT * FROM public.books WHERE lower(title) = '図書館の本07';
RESET enable_seqscan;`,
      check: { type: 'sql', sql: `SELECT (SELECT count(*) FROM pg_indexes
         WHERE schemaname = 'public' AND tablename = 'books'
           AND indexname = 'books_title_lower_idx'
           AND position('lower' in indexdef) > 0 AND position('title' in indexdef) > 0) = 1` },
      mysqlNote: 'MySQL 8.0.13 以降は**関数索引**（functional index）`CREATE INDEX ... ON books ((lower(title)));` が使えます（二重括弧が MySQL 流）。それ以前のバージョンでは、`lower(title)` を格納する**生成列**を作ってその列に索引を付けるのが定番でした。PostgreSQL の式索引と発想は同じですが、MySQL では「生成列で実質式索引」の歴史が長く、移行先のバージョン確認が重要です。' },
    { id: 'ch08-09', title: '索引が使われない4つのケース', session: 'A',
      story: '索引を作ったのに遅い——実務で一番よくある形のトラブルです。索引が使われない典型パターンを4つ、この蔵書データで確認しておきます。原因を知っていれば、対処はすぐです。',
      explanation: '## ① 列に演算・関数をかけた\n```sql\nEXPLAIN (COSTS OFF) SELECT * FROM public.books WHERE upper(title) = \'図書館の本07\';\n```\n`lower(title)` の索引を作りましたが、**`upper(title)` には使えません**。索引は「入れた式そのもの」にしか効きません。列に CAST をかけた場合も同じです:\n```sql\nEXPLAIN (COSTS OFF) SELECT * FROM public.loan_history WHERE history_id::text = \'12345\';\nEXPLAIN (COSTS OFF) SELECT * FROM public.loan_history WHERE history_id = 12345;\n```\n上は Seq Scan、下は主キーの Index Scan。`::text` を付けただけで計画が変わります。**検索側を式索引に合わせる**か、**式を検索側から外す**のが対処です（パラメータは正しい型で渡す、という意味でもあります）。\n\n## ② 前方不一致の LIKE\n```sql\nEXPLAIN (COSTS OFF) SELECT * FROM public.books WHERE title LIKE \'%本07\';\n```\n`%` で始まる LIKE は索引を**原理的に**使えません（先頭が分からないと、ソートされた木を探せない）。前方一致 `LIKE \'図書%\'` なら B-tree が使えます（locale が C の環境や text_pattern_ops 併用）。**検索仕様の変更**（後方一致をやめる、または逆順インデックス）が本質的な対処です。\n\n## ③ 選択度が低い（該当が多すぎる）\n```sql\nEXPLAIN SELECT * FROM public.loan_history WHERE member_id IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16);\n```\nmember_id には索引（ch08-05）があります。でもこの問い合わせは80万行（80%）を要求します。**全件走査の方が速いとプランナが正しく判断**し、Seq Scan になります。索引は「少数を取る」道具であって、多数を取るための道具ではありません。WHERE の条件が甘い（絞れていない）ことのサインと読みます。\n\n## ④ 統計が古い / 見積もりが当てにならない\nANALYZE されていない、またはデータが激変した後は、プランナが「索引を使う価値」を誤判断します。前のステップの相関のズレ（見積140行・実際1370行）のように、**見積もりと実測が離れている計画を見たら統計を疑う**のが定石です。\n\n**なぜ実務でこうするか**: 「索引を足せば速くなる」は嘘で、「**問い合わせの形に合った**索引を作り、EXPLAIN で確認する」が本当です。この4パターンを知っているだけで、索引の乱造（書き込みを遅くするだけの索引）を防げます。',
      task: '模範解答の EXPLAIN を実行して、4つのケース（関数/キャスト、前方不一致 LIKE、低選択度、比較対象のCAST）がすべて Seq Scan になることを確認してください。読めたら「読ました・次へ進む準備」です。',
      hints: ['EXPLAIN (COSTS OFF) を付けると計画の骨格だけを見られます。', 'history_id = 12345（キャストなし）が Index Scan になることを、::text 版と見比べます。', 'IN (...) のリストは1〜16の16個です。80%に相当します。'],
      solution: `EXPLAIN (COSTS OFF) SELECT * FROM public.books WHERE upper(title) = '図書館の本07';
EXPLAIN (COSTS OFF) SELECT * FROM public.books WHERE title LIKE '%本07';
EXPLAIN SELECT * FROM public.loan_history WHERE member_id IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16);
EXPLAIN (COSTS OFF) SELECT * FROM public.loan_history WHERE history_id::text = '12345';
EXPLAIN (COSTS OFF) SELECT * FROM public.loan_history WHERE history_id = 12345;`,
      replay: '',
      check: { type: 'manual' },
      mysqlNote: 'この4つは MySQL でもほぼ同じ現象になります: ①列に関数をかけると索引不可（5.7以前は顕著。8.0でも式が一致しないと不可）、②前方不一致 LIKE は不可、③該当が多いと type=ALL、④統計は ANALYZE TABLE で更新。PostgreSQL と MySQL で語彙が違うだけで、**索引が効く原理（ソートされた木を左から探す）は同じ**です。' },
    { id: 'ch08-10', title: '索引の維持費 — 書き込みと索引の切っても切れない関係', session: 'A',
      story: '索引を作りすぎた表が、書き込み性能に響く——当たり前のことですが、目に見えないので軽視されがちです。この章の締めくくりに、索引のコストと、PostgreSQL の DDL の安全さを組み合わせた実験をします。',
      explanation: '## 索引は「読み」を速く、「書き」を重くする\n表に行を INSERT すると、**その表の索引すべて**に「どのページのどこに置いたか」を書き込みます。この章で loan_history に作った索引は3本（member、member+date、open）。つまり100万行の投入時に、素の表なら1か所だった書き込みが **表 + 3本の索引 = 4か所** になっています。\n\nコストの内訳:\n- **INSERT** — 索引の数だけ木を更新（葉が詰まるとページ分割も）\n- **UPDATE** — 索引列を変えたら、古い索引エントリを消して新しい位置に挿入。**索引に含まれない列だけの UPDATE** なら、PostgreSQL は **HOT（Heap-Only Tuple）** という最適化で索引を触らずに済みます\n- **DELETE** — 行の可視性だけを変え、索引エントリは VACUUM まで残る（次のステップのテーマ）\n\nだから運用では「**本当に使われているか**」を確認して使われない索引を落とします:\n```sql\nSELECT relname AS index_name, idx_scan AS scans\nFROM pg_stat_user_indexes\nWHERE schemaname = \'public\' AND relname LIKE \'loan_history%\'\nORDER BY idx_scan DESC;\n```\n\n## DDL はトランザクションできる（の復習）\n2章の最後で体験したとおり、PostgreSQL の DROP INDEX もトランザクションの中で実行でき、ROLLBACK で取り消せます。**実務のメンテナンス作業は「BEGIN → 変更 → 確認 → COMMIT」で行う**と、深夜のオペレーションミスを安全に復帰できます（MySQL の DDL は暗黙コミットされるので、この安心感は PostgreSQL の大きな利点です）。\n\n**なぜ実務でこうするか**: 読み取りを速くする索引の「請求書」は書き込みに届きます。索引を増やす前に「この WHERE の形が本当に頻出か」を疑い、増やした後は idx_scan で使われたかを見る——この往復が索引のライフサイクル管理です。',
      task: 'BEGIN → DROP INDEX loan_history_member_idx → 確認 SELECT → ROLLBACK → 確認 SELECT を1回の送信で実行してください。索引が ROLLBACK で復活することを、最後の SELECT で採点します。',
      hints: ['BEGIN; DROP INDEX public.loan_history_member_idx; SELECT count(*)::int AS member_indexes FROM pg_indexes WHERE ... AND indexname = \'loan_history_member_idx\'; で索引が0本になったことを確認します。', 'ROLLBACK; した後、同じ SELECT で1本に戻っていることを確認します。', '最後の SELECT が採点対象です（loan_history_member_idx が存在する=1 になる）。'],
      solution: `BEGIN;
DROP INDEX public.loan_history_member_idx;
SELECT count(*)::int AS member_indexes FROM pg_indexes
WHERE schemaname = 'public' AND tablename = 'loan_history' AND indexname = 'loan_history_member_idx';
ROLLBACK;
SELECT count(*)::int AS member_indexes FROM pg_indexes
WHERE schemaname = 'public' AND tablename = 'loan_history' AND indexname = 'loan_history_member_idx';`,
      replay: '',
      check: { type: 'result-equals', expectedSql: `SELECT count(*)::int AS member_indexes FROM pg_indexes
WHERE schemaname = 'public' AND tablename = 'loan_history' AND indexname = 'loan_history_member_idx'` },
      mysqlNote: 'MySQL の InnoDB も同様に、書き込みで全ての二次索引を更新します。MySQL は **Change Buffer** で二次索引ページがメモリに無いときの更新を遅延させる独自工夫があります（PostgreSQL に相当機能はありません）。DDL は決定的な違いで、MySQL の ALTER TABLE ... DROP INDEX は**暗黙コミット**され、ロールバック不可能です。メンテナンス手順書の「失敗時に戻す」が、MySQL ではバックアップ前提になる点に注意します。' },
    { id: 'ch08-11', title: 'VACUUM — MVCC の掃除と統計の更新', session: 'A',
      story: '最後に、PostgreSQL の「見えない仕事」を扱います。ROLLBACK した行、削除した行——それらはどこへ行くのでしょう。',
      explanation: '## PostgreSQL の行は「消してもすぐには消えない」\nPostgreSQL は更新・削除で行を上書きせず、**古い版の行を置き去りにして新しい版を作ります**（MVCC: 多版同時制御。ROLLBACK のたびに「誰にも見えない死んだ行」が残ります）。9章で大量の ROLLBACK を経験しますが、そのたびにゴミが溜まります。\n\nこのゴミを回収するのが **VACUUM** です。\n```sql\nVACUUM public.loan_history;\n```\n- 死んだ行の領域を**表の中で再利用可能**にします（OSにファイルを返すわけではない）\n- **可視性マップ（Visibility Map）** を更新します。このビットが立ったページは「全行が全トランザクションから見える」ので、索引のみのスキャン（Index Only Scan）や凍結処理の高速化に使われます\n- VACUUM は autovacuum が自動で実行してくれるので、**手動は特別なタイミング**（大量ロード後、大批量更新後）に絞るのが実務です\n- `VACUUM ANALYZE 表名;` で統計採取（ANALYZE）も同時にできます\n\n## VACUUM の2つの約束\n1. **VACUUM はトランザクションの中で実行できません**（エラー 25001）。バッチの途中でなく、**単独の文**として実行します（このステップも solution がそれだけです）\n2. `VACUUM FULL` はファイルを縮小しますが、**排他ロック**を取るので業務時間帯には使いません。通常の VACUUM は読み書きと並行で走ります\n\n**なぜ実務でこうするか**: 「更新が多い表がだんだん遅い」「ディスクが減らない」は、VACUUM（と autovacuum の調整）で解決する定番の現象です。PostgreSQL を選ぶ限り、MVCC と VACUUM の関係は避けて通れません。',
      task: 'VACUUM public.loan_history; を単独の文で実行してください（BEGIN で囲んではいけません）。採点は pg_stat_user_tables に手動 VACUUM の記録が残ることで行います。',
      hints: ['VACUUM public.loan_history; だけを送信します（他の文と混ぜない）。', 'BEGIN; VACUUM ...; は 25001 エラーになるので注意してください。', 'ANALYZE を同時にやりたければ VACUUM ANALYZE ですが、このステップは VACUUM 単体です。'],
      solution: 'VACUUM public.loan_history;',
      replay: '',
      check: { type: 'sql', sql: `SELECT (SELECT count(*) FROM pg_stat_user_tables
         WHERE schemaname = 'public' AND relname = 'loan_history' AND last_vacuum IS NOT NULL) = 1` },
      mysqlNote: 'MySQL（InnoDB）には VACUUM がありません。削除・更新の跡は** purge スレッド**がアンドゥログを遡って掃除し、領域は表領域に返されます（ただし縮小はされない）。ファイルを縮小したいときは `OPTIMIZE TABLE`（表の作り直し、PostgreSQL の VACUUM FULL に近い）を使います。「消したはずなのにディスクが減らない」は両方に共通する現象で、PostgreSQL なら VACUUM、MySQL なら purge/optimize が対応策です。' },
  ],
}
export default chapter
