import type { Chapter } from '../src/shared/lessons.js'
const chapter: Chapter = {
  id: 9, title: 'トランザクション', summary: '二つのセッションで分離・競合・ロックを体験します。',
  steps: [
    { id: 'ch09-01', title: 'BEGIN と ROLLBACK — まとめて成功、まとめて失敗', session: 'A',
      story: '開館して人が増え、業務は「同時進行」の時代に入りました。その前に、1人の作業の「区切り」を完璧にしましょう。司書が「会員登録の途中でやっぱり取りやめ」と言ったとき、中途半端な行が残らないようにします。',
      explanation: '## トランザクションは「1つの仕事のまとまり」\n```sql\nBEGIN;               -- ここから始める\nINSERT INTO ... ;     -- 仕事\nROLLBACK;            -- なかったことにする（COMMIT なら確定）\n```\n- `BEGIN` から `COMMIT` / `ROLLBACK` までが**1つのトランザクション**\n- **COMMIT** … ここまでの変更をすべて確定。**取り消せない**（この教材ではやり直しがきくだけの話で、本番ではそうではありません）\n- **ROLLBACK** … ここまでの変更をすべて破棄。失敗した夜間バッチを巻き戻すときの標準手段です\n- BEGIN 〜 COMMIT の中の**複数の文は「全か無か」**。3文のうち1文でも失敗すれば、ROLLBACK したとき3文とも消えます\n\n今まで特に意識せずに使ってきた INSERT は、実は**1文だけの暗黙のトランザクション**（自動コミット）でした。1文で終わる仕事は BEGIN を書かなくてよい、というだけの話です。\n\nこのステップでは、仮の会員（ID 99）を登録してから ROLLBACK で消します。トランザクションの中では**自分の変更が自分から見える**（SELECT で 21 になる）点も確認してください。\n\n**なぜ実務でこうするか**: 「会員を登録して、次に初期貸出を登録して、最後にポイントを発行する」のような複数ステップの業務は、途中で失敗すると業務として不完全です。トランザクションは「業務の1単位」と「SQL の1単位」を一致させる、アプリケーション設計の土台です。',
      task: 'BEGIN → 仮会員（ID 99）を INSERT → SELECT で21人を確認 → ROLLBACK → SELECT で20人に戻ることを確認してください。',
      hints: ['BEGIN; INSERT INTO public.members (member_id, name) VALUES (99, \'体験会員\'); で始めます（ID を明示するので採番は進みません）。', 'トランザクション中の SELECT count(*) では、自分の未コミット行も見えます。', 'ROLLBACK; の後、同じ SELECT で20に戻ることを確認してから採点します。'],
      solution: `BEGIN;
INSERT INTO public.members (member_id, name) VALUES (99, '体験会員');
SELECT count(*)::int AS members FROM public.members;
ROLLBACK;
SELECT count(*)::int AS members FROM public.members;`,
      replay: '',
      check: { type: 'result-equals', expectedSql: 'SELECT count(*)::int AS members FROM public.members' },
      mysqlNote: 'BEGIN / COMMIT / ROLLBACK は MySQL も同じです（START TRANSACTION が正式名で BEGIN は別名）。MySQL では**暗黙コミット**に注意: DDL（CREATE TABLE 等）を実行すると、それより前の変更が勝手に COMMIT されます。PostgreSQL は DDL もトランザクション内なので、この点は設計判断そのものが変わるほどの違いです（2章参照）。' },
    { id: 'ch09-02', title: 'ACID — 図書館業務で考える4つの性質', session: 'A',
      story: '司書の端末が2台になり、同時作業の前に理論の全体像を整理します。データベースがトランザクションで約束してくれる4つの性質、ACID を図書館の言葉で説明します。',
      explanation: '## A — Atomicity（原子性）: 「貸出と蔵書状態は一体」\n貸出の INSERT を行うと、7章のトリガーが copies.status を loaned に変えます。この2つの変更は**不可分**です。INSERT が失敗すれば蔵書状態の変更も消え、逆も同じ。「半分だけ登録された貸出」は存在できません。複数文のバッチでも、BEGIN〜COMMIT の中は全か無かです。\n\n## C — Consistency（一貫性）: 「業務ルールは常に守られる」\n「貸出済みの蔵書は貸せない」（7章のトリガー 23514）、「同じ蔵書の未返却貸出は1件まで」（2章の一意索引 23505）、「価格は0以上」（CHECK 制約）。**どのトランザクションも、これらのルールを破った状態で終わることはできません**。制約・トリガー・一意索引が「一貫した状態」を定義し、トランザクションは状態から状態へ壊さずに移すだけです。\n\n## I — Isolation（分離性）: 「2つの窓口が同時に動いても、正しい順序で実行したのと同じ結果にする」\n**この章の主役**です。2つの窓口が同じ本を貸し出そうとする、同じ会員のデータを同時に直す——分離レベル（READ COMMITTED / REPEATABLE READ / SERIALIZABLE）は「他の作業がどこまで見えるか」の契約です。残りのステップですべて体験します。\n\n## D — Durability（永続性）: 「COMMIT したら、落ちても消えない」\nCOMMIT が返ってきた瞬間、その変更は**WAL（先読み込みジャーナル）**にディスクへ書き出されています。直後にサーバーが落ちても、再起動時に WAL を再生して COMMIT 済みの変更を復元します。9章の終わり頃に「トランザクションログ」としてまた会います。\n\n**なぜ実務でこうするか**: ACID は「データベースを信頼して良い理由」の目録です。アプリが壊れても、人がミスしても、サーバーが落ちても、この4つだけはデータベースが守る——だからアプリの設計は失敗時に ROLLBACK して済みます。\n\n模範解答は、7章の貸出トリガーの体験の原子性をもう一度確かめる自己学習用の SQL です（実行しても何も残りません）。',
      task: 'ACID の説明を読み、模範解答の貸出+取消しをもう一度体験したら「読ました・次へ進む準備」を押してください。',
      hints: ['Atomicity・Consistency・Isolation・Durability の頭文字です。', '模範解答は BEGIN 〜 ROLLBACK で囲まれているので、実行しても何も残りません。'],
      solution: `BEGIN;
INSERT INTO public.loans (loan_id, copy_id, member_id, due_on) VALUES (103, 3, 1, CURRENT_DATE + 14);
SELECT copy_id, status AS in_loan FROM public.copies WHERE copy_id = 3;
ROLLBACK;
SELECT (SELECT count(*)::int FROM public.loans WHERE loan_id = 103) AS loan_rows,
       (SELECT status FROM public.copies WHERE copy_id = 3) AS copy_status;`,
      replay: '',
      check: { type: 'manual' },
      mysqlNote: 'MySQL（InnoDB）も ACID を実装しますが、部品の名前が違います: 永続性は **redo ログ**（WAL 相当）と **doublewrite バッファ**、原子性は **undo ログ**（ロールバック情報を先に書く。PostgreSQL は「古い版をそのまま残す」方式で、undo ログは不要）。この差が「PostgreSQL は VACUUM が必要、MySQL は purge が必要」という8章の運用差にそのままつながっています。' },
    { id: 'ch09-03', title: 'SAVEPOINT — 失敗した処理だけを巻き戻す', session: 'A',
      story: 'ある司書が困っていました。「会員登録をしながら、ついでに価格訂正も1つのトランザクションでやっていたら、価格のミスで全体が巻き戻ってしまった」。失敗した部分だけやり直したい——そのための仕組みがあります。',
      explanation: '## トランザクションの中に「巻き戻し地点」を作る\n```sql\nBEGIN;\nINSERT INTO ... ;              -- ① これは残したい\nSAVEPOINT sp;                 -- ② 地点を置く\nUPDATE ... ;                   -- ③ ここで失敗（トランザクションが failed になる）\nROLLBACK TO SAVEPOINT sp;     -- ④ ③だけを巻き戻して、続きができる\nCOMMIT;                        -- ①は確定される\n```\n失敗の挙動を正確に知っておく必要があります。PostgreSQL は、トランザクション内の1文が失敗すると、そのトランザクションを **failed 状態**にして、それ以上の文を受け付けません（25P02 エラー）。**SAVEPOINT を切ってあれば、`ROLLBACK TO SAVEPOINT` でそこまで戻って作業を続行できます**。切っていなければ、トランザクション全体を ROLLBACK するしかありません。\n\n実務の使いどころ:\n- バッチ処理で「1件だけおかしい行があっても、その行を飛ばして全体は止めない」（エラー行をログに残して ROLLBACK TO SAVEPOINT）\n- 長い作業の「仮確定ポイント」\n\nこのステップはガイド付きスクリプトです。**1行ずつ、ガイドの順番どおりに実行**してください（価格を -100 にする UPDATE は、CHECK 制約でわざと失敗させます）。\n\n**なぜ実務でこうするか**: 「1件のゴミで夜間バッチ全体が落ちる」を防ぐ定番道具です。例外処理と ROLLBACK TO SAVEPOINT の組み合わせは、PL/pgSQL の例外ブロック（EXCEPTION節）の中身でもあります（7章のトリガー関数と同じ PL/pgSQL の知識です）。',
      task: 'ガイドに沿って、セッション A で: BEGIN → 仮会員（ID 99）を INSERT → SAVEPOINT → 価格違反の UPDATE（23514 で失敗）→ ROLLBACK TO SAVEPOINT → 会員が残っていることを確認 → ROLLBACK。',
      hints: ['スクリプトの各行を「このSQLを挿入」ボタンでエディタに入れて、順番に1つずつ実行します。', 'UPDATE public.books SET price = -100 WHERE book_id = 1; は books_price_check で 23514 になります。', 'ROLLBACK TO SAVEPOINT sp_before_price; の後、SELECT で会員99がまだ見えることを確認します。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN;', expect: 'ok', note: 'トランザクションを開始します。' },
        { session: 'A', sql: "INSERT INTO public.members (member_id, name) VALUES (99, '仮登録会員');", expect: 'ok', note: '① 残したい変更（会員ID 99 を明示指定）。' },
        { session: 'A', sql: 'SAVEPOINT sp_before_price;', expect: 'ok', note: '② 巻き戻し地点を置きます。' },
        { session: 'A', sql: 'UPDATE public.books SET price = -100 WHERE book_id = 1;', expect: { errorCode: '23514' }, note: '③ books_price_check 違反で失敗。以後このトランザクションは failed 状態になります。' },
        { session: 'A', sql: 'ROLLBACK TO SAVEPOINT sp_before_price;', expect: 'ok', note: '④ ③だけを巻き戻します。トランザクションは再び使える状態に戻ります。' },
        { session: 'A', sql: 'SELECT count(*)::int AS temp_members FROM public.members WHERE member_id = 99;', expect: 'ok', note: '①の会員は生きているはずです（1行）。' },
        { session: 'A', sql: 'ROLLBACK;', expect: 'ok', note: '実験を終了。会員99も消えて、何も残りません。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL にも SAVEPOINT / ROLLBACK TO SAVEPOINT があり、構文は同じです。大きな違いは失敗時: PostgreSQL のトランザクションは1文のエラーで failed 状態になり** SAVEPOINT が無い限り続行できません**が、MySQL（InnoDB）はエラー後も**トランザクションを続行できます**（エラーになった文だけが無視される）。この挙動差は、移行したアプリのエラー処理で事故になりやすいポイントです。' },
    { id: 'ch09-04', title: 'READ COMMITTED — 読むたびに世界が変わる', session: 'AB',
      connect: { A: { user: 'admin', password: '', database: 'library' }, B: { user: 'admin', password: '', database: 'library' } },
      story: 'いよいよ2窓口の同時作業です。まず PostgreSQL の既定の分離レベル READ COMMITTED で、「他の窓口のコミットが、こちらの読み取りに割り込んでくる」現象を観察します。',
      explanation: '## 既定の分離レベル READ COMMITTED\nREAD COMMITTED は「**1文ごとに、最新のコミット済みデータを見る**」という契約です。トランザクションの中でも、文のたびに世界は進んで見えます。\n\n観察するシナリオ（ガイドの順番どおりに）:\n1. **A** が本1の価格を読む → 600\n2. **B** が本1の価格を 999 に変えて **COMMIT** する\n3. **A** がもう一度読む → **999** が見える！\n\n同じトランザクションの中で、同じ SELECT なのに結果が変わりました。これが**非再現リード（non-repeatable read）**です。\n\n## これはバグか？\nいいえ、契約どおりの挙動です。READ COMMITTED は「長い読み取りの一貫性」より「最新コミットの反映」を優先する、この上なく実用的な契約です:\n- 短い Web アプリのリクエスト（読んで終わる）には十分\n- 1つの業務が「1画面のうちに終わる」設計なら、非再現リードに意味はあまりない\n- しかし「合計を2回計算して一致を確認する」のような、トランザクション内の**一貫した見え**を要求する業務には不足します\n\n**なぜ実務でこうするか**: 分離レベルは性能と一貫性のトレードオフです。READ COMMITTED はロックが最小で並行性が最大。ほとんどの Web アプリはこの既定で動いています。「読みの一貫性」が必要な業務箇所だけ、次のステップの REPEATABLE READ を検討します。\n\n最後のガイド行で、B が価格を 500 + book_id × 100（本1なら600、seed の正規形）に復元します。',
      task: 'ガイドに沿って: A で読む → B で変えて COMMIT → A で再読（999 が見える）→ A を ROLLBACK → B で復元。すべての行を順番どおりに実行してください。',
      hints: ['A は BEGIN してから2回 SELECT します。この2回の間に B の変更が COMMIT されます。', 'B の COMMIT は必ず A の2回目の SELECT より前に実行します。', '最後の復元は UPDATE public.books SET price = 500 + book_id * 100 WHERE book_id = 1; です。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN;', expect: 'ok', note: 'A: トランザクションを開始します。' },
        { session: 'A', sql: 'SELECT price FROM public.books WHERE book_id = 1;', expect: 'ok', note: 'A: 1回目の読み取り。600 のはずです。' },
        { session: 'B', sql: 'BEGIN;', expect: 'ok', note: 'B: もう1つの窓口のトランザクションです。' },
        { session: 'B', sql: 'UPDATE public.books SET price = 999 WHERE book_id = 1;', expect: 'ok', note: 'B: 価格を 999 に変更（未コミット）。A からはまだ見えません。' },
        { session: 'B', sql: 'COMMIT;', expect: 'ok', note: 'B: 確定。ここから全員に 999 が見えます。' },
        { session: 'A', sql: 'SELECT price FROM public.books WHERE book_id = 1;', expect: 'ok', note: 'A: 2回目の読み取り。999 が見える = 非再現リード！' },
        { session: 'A', sql: 'ROLLBACK;', expect: 'ok', note: 'A: 読み取りだけのトランザクションを閉じます。' },
        { session: 'B', sql: 'UPDATE public.books SET price = 500 + book_id * 100 WHERE book_id = 1;', expect: 'ok', note: 'B: seed の正規形（600）に復元して実験を終えます。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL の既定も REPEATABLE READ で、READ COMMITTED は `SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;` で明示します。「1文ごとに最新コミットを見せる」挙動は同じです。MySQL の RC は半一貫読み（semi-consistent read）という InnoDB 独自の読み方もあります（更新用の現在読みと組み合わせた挙動）。' },
    { id: 'ch09-05', title: 'REPEATABLE READ — スナップショットの一貫性と 40001', session: 'AB',
      story: '「非再現リードは困る」という業務には、次の契約があります。REPEATABLE READ は、トランザクションの最初に世界の**スナップショット（写真）**を撮り、自分が終わるまでそれを見続けます。',
      explanation: '## BEGIN の瞬間の世界を見続ける\n`BEGIN ISOLATION LEVEL REPEATABLE READ;` で、そのトランザクションは「**BEGIN した時点でコミット済みだったデータ**」だけを見ます。8章で学んだ MVCC の仕組みそのもので、他のセッションのコミットは**自分の写真には映りません**。\n\n観察するシナリオ:\n1. **A** が REPEATABLE READ で開始し、本1の価格を読む → 600\n2. **B** が 999 に変えて COMMIT（この時点で「本当の」価格は 999）\n3. **A** が再読 → **まだ 600**。スナップショットの一貫性が保たれています\n4. **A** が価格を更新しようとする → **エラー 40001** で失敗！\n\n4番が重要です。**古い写真を見ながら書くことは許されません**。A の読んだ価格（600）はもう過去のものなので、PostgreSQL は「更新の対象が自分の知らない間に変わっていた」と検出して、更新を 40001（直列化失敗）で拒否します。A は ROLLBACK して、新しい世界でやり直します。\n\nこれが READ COMMITTED との決定的な違いです:\n- READ COMMITTED: 更新は**最新版を読み直して**実行される（割り込まれても上書きされる）\n- REPEATABLE READ: 更新対象がスナップショットと違っていたら**拒否する**（安全側に倒す）\n\n**なぜ実務でこうするか**: 「読み取りたびに金額が変わると合計が合わない」レポートや、長い分析処理に REPEATABLE READ は有効です。しかし「読んでから書く」なら競合時にやり直しが必要になる——この「やり直し」の設計（アプリのリトライ）が同時実行設計の本丸です。',
      task: 'ガイドに沿って: A が REPEATABLE READ で読む → B が変えて COMMIT → A が再読（600 のまま）→ A が更新（40001）→ A ROLLBACK → B 復元。',
      hints: ['A の最初の文は BEGIN ISOLATION LEVEL REPEATABLE READ; です（分離レベル指定は BEGIN の文で行います）。', 'A の更新 UPDATE public.books SET price = 777 WHERE book_id = 1; は 40001 で失敗します。失敗後は ROLLBACK が必要です。', 'B の復元は前のステップと同じ UPDATE ... SET price = 500 + book_id * 100 です。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN ISOLATION LEVEL REPEATABLE READ;', expect: 'ok', note: 'A: スナップショット撮影つきで開始します。' },
        { session: 'A', sql: 'SELECT price FROM public.books WHERE book_id = 1;', expect: 'ok', note: 'A: 1回目。600 を写真に収めます。' },
        { session: 'B', sql: 'BEGIN;', expect: 'ok', note: 'B: 既定（READ COMMITTED）のトランザクションです。' },
        { session: 'B', sql: 'UPDATE public.books SET price = 999 WHERE book_id = 1;', expect: 'ok', note: 'B: 999 に変更。' },
        { session: 'B', sql: 'COMMIT;', expect: 'ok', note: 'B: 確定。世界は 999 に進みました。' },
        { session: 'A', sql: 'SELECT price FROM public.books WHERE book_id = 1;', expect: 'ok', note: 'A: 再読。まだ 600 のまま（スナップショットの一貫性）。' },
        { session: 'A', sql: 'UPDATE public.books SET price = 777 WHERE book_id = 1;', expect: { errorCode: '40001' }, note: 'A: 古い写真を信じた更新は拒否されます（40001）。トランザクションは failed 状態に。' },
        { session: 'A', sql: 'ROLLBACK;', expect: 'ok', note: 'A: 失敗したトランザクションを閉じます。' },
        { session: 'B', sql: 'UPDATE public.books SET price = 500 + book_id * 100 WHERE book_id = 1;', expect: 'ok', note: 'B: seed の正規形（600）に復元します。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL の**既定**は REPEATABLE READ です（PostgreSQL の既定は READ COMMITTED）。どちらも「スナップショットを見る」点は同じですが、PostgreSQL は競合する更新を 40001 で拒否します。MySQL の InnoDB は競合時、**ロックが解放されたら最新版を読み直して更新を続行**します（PostgreSQL の READ COMMITTED に近い挙動）。つまり同名の REPEATABLE READ でも、競合時の挙動が逆——移行時には必ず見る違いです。' },
    { id: 'ch09-06', title: 'SERIALIZABLE — 「読んで判断して書く」の同時失敗（書きスキュー）', session: 'AB',
      story: '会員1の貸出上限は2冊と決まりました。現在の貸出中は1冊。2つの窓口が同時に「今1冊だから、もう1冊貸せる」と判断して、それぞれ別の本を貸し出したら——上限3冊でルール違反です。前2つのレベルでは検出できない競合です。',
      explanation: '## 書きスキュー（write skew）— 現れると困る、隠れると検出できない競合\nシナリオ（ガイドどおり）:\n1. **A** と **B** が両方 SERIALIZABLE で開始\n2. 両方が「会員1の貸出中は何冊？」を調べる → 両方とも **1冊**\n3. **A** が蔵書1を、**B** が蔵書2を、同じ会員1に貸し出す（別々の行！）\n4. **A** が COMMIT → 成功。**B** が COMMIT → **40001 で失敗！**\n\nREAD COMMITTED でも REPEATABLE READ でも、この2つの COMMIT は**両方成功**します。どちらも他者が書いた行と衝突していないからです（「調べた結果」だけが古い）。SERIALIZABLE だけが、「会員1の貸出中の行」を読んだ両者が loans に書いた、という**読み書き依存の循環**を検出して、後から COMMIT した側を中止します。\n\nこの「検査してから書く（check-then-act）」パターンの防御手段を整理すると:\n- 一意索引 … 同じ行を2重に書く場合のみ防御（今回は別行なので効かない）\n- FOR UPDATE … 検査する対象行を固定できれば防御（次々ステップ。しかし今回は「存在しない行」を検査しているので固定できない）\n- SERIALIZABLE … **パターンを問わず、順序がおかしい並行を自動検出**。代償は競合時の 40001 とリトライ\n\n失敗した側のアプリの正しい反応は**リトライ**（トランザクションを最初からやり直す）です。「COMMIT が 40001 で失敗する」のは SERIALIZABLE の正常な動作で、データは壊れていません。\n\n**なぜ実務でこうするか**: 「在庫を確認してから減らす」「残高を確認してから振り込む」は、どのシステムにもあるパターンです。ロジックの正しさを1つ1つ FOR UPDATE で証明するより、「SERIALIZABLE で全部守って、失敗したらリトライ」という設計の方が、ミスが少なくて済む場合があります（競合率が低い業務に向きます）。',
      task: 'ガイドに沿って: A・B が SERIALIZABLE で会員1の貸出数を調べる → A・B が別々の蔵書（1と2）を会員1に貸出 → A COMMIT（成功）→ B COMMIT（40001）→ B ROLLBACK → A が復元。',
      hints: ['両方とも BEGIN ISOLATION LEVEL SERIALIZABLE; で開始します。', 'INSERT する貸出は A が ID 101（蔵書1）、B が ID 102（蔵書2）、会員はどちらも 1 です。', 'B の COMMIT は 40001 で失敗します。失敗したら ROLLBACK して、最後に A が貸出と蔵書状態を復元します。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN ISOLATION LEVEL SERIALIZABLE;', expect: 'ok', note: 'A: SERIALIZABLE で開始します。' },
        { session: 'B', sql: 'BEGIN ISOLATION LEVEL SERIALIZABLE;', expect: 'ok', note: 'B: 同じく SERIALIZABLE で開始します。' },
        { session: 'A', sql: 'SELECT count(*)::int AS open_loans FROM public.loans WHERE member_id = 1 AND returned_on IS NULL;', expect: 'ok', note: 'A: 会員1の貸出中は 1 冊。「もう1冊貸せる」と判断します。' },
        { session: 'B', sql: 'SELECT count(*)::int AS open_loans FROM public.loans WHERE member_id = 1 AND returned_on IS NULL;', expect: 'ok', note: 'B: 同じ検査で同じく 1 冊。同じ判断に立ちます。' },
        { session: 'A', sql: 'INSERT INTO public.loans (loan_id, copy_id, member_id, due_on) VALUES (101, 1, 1, CURRENT_DATE + 14);', expect: 'ok', note: 'A: 蔵書1を会員1に貸出（トリガーが蔵書1を loaned にします）。' },
        { session: 'B', sql: 'INSERT INTO public.loans (loan_id, copy_id, member_id, due_on) VALUES (102, 2, 1, CURRENT_DATE + 14);', expect: 'ok', note: 'B: 蔵書2を会員1に貸出。別の行なので、ここではまだ衝突しません。' },
        { session: 'A', sql: 'COMMIT;', expect: 'ok', note: 'A: 先に確定した側が勝ちます。' },
        { session: 'B', sql: 'COMMIT;', expect: { errorCode: '40001' }, note: 'B: 読み書き依存の循環を検出され、COMMIT が 40001 で拒否されます（書きスキューの検出）。' },
        { session: 'B', sql: 'ROLLBACK;', expect: 'ok', note: 'B: 失敗したトランザクションを閉じます（蔵書2の貸出は消えます）。' },
        { session: 'A', sql: "BEGIN; DELETE FROM public.loans WHERE loan_id = 101; UPDATE public.copies SET status = 'available' WHERE copy_id = 1 AND status = 'loaned'; COMMIT;", expect: 'ok', note: 'A: 実験で確定した貸出を復元し、seed を元に戻します。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL には SERIALIZABLE もあります（`SET TRANSACTION ISOLATION LEVEL SERIALIZABLE`）が、実装が違います: MySQL の SERIALIZABLE は「すべての読み取りを暗黙に LOCK IN SHARE MODE（共有ロック付き読み）にする」**悲観的なロック方式**です。PostgreSQL の SERIALIZABLE はロックを取らずに依存グラフで検出する SSI（直列化可能スナップショット分離）方式。どちらも「正しくない並行は失敗させる」契約ですが、PostgreSQL は読み取りがロックを取らない分、並行性が高いかわりに検出がコミット時になります。' },
    { id: 'ch09-07', title: '失われた更新 — 同じ値を読んで、別々に書く', session: 'AB',
      story: '価格改定の季節です。A と B の両窓口が「本1の価格（600円）に200円の値上げをしよう」と相談して、それぞれ 800 と 700 を書き込みました。結果は 700。A の更新はどこへ行ったのでしょう。',
      explanation: '## ロストアップデート（失われた更新）\nガイドのシナリオ:\n1. **A** と **B** が両方 600 を読む\n2. **A** が 800 を書く（まだ COMMIT していないので、行ロックを握る）\n3. **B** が 700 を書こうとして、**A のロック待ちでブロック**される\n4. **A** が COMMIT → B の書き込みが通り、結果は **700**\n5. **A の 800 は消えました**。誰もエラーを見ていません\n\nポイントは **3** です。READ COMMITTED の更新文は「待たされた後、**最新の行版を読み直して**」実行されます。エラーにはならない——ただ、B が「600 を読んで決めた 700」を、最新の 800 に対して上書きします。**黙って上書きするのが READ COMMITTED の契約**なのです（前のステップの REPEATABLE READ なら、ここは 40001 で拒否されました）。\n\n予防策（使い分け）:\n- **相対更新に書き換える**: `SET price = price + 200` なら、「待たされた後に読み直した値」を基準に計算するので安全（READ COMMITTED で OK）\n- **FOR UPDATE で先にロックして読む**: 読み取った時点で行を押さえる（次のステップ）\n- **REPEATABLE READ / SERIALIZABLE**: 衝突を 40001 で検出してリトライ\n\n**なぜ実務でこうするか**: 「カートの合計を計算してから保存」「残高を読んでから引く」——読んだ値を使って別の値を書くコードはアプリのどこにでもあります。READ COMMITTED の契約は「黙って最新に置き換わる」なので、金額や在庫のような行では**このパターン自体を禁じる**のが同時実行設計の定石です。',
      task: 'ガイドに沿って: A・B とも 600 を読む → A が 800 を書く → B が 700 を書く（ブロック）→ A COMMIT → B が 700 を確認 → B ROLLBACK → A が復元。',
      hints: ['「値を読んで、その値を元に計算した別の値を書く」のが危険パターンです。ここでは A は 800、B は 700 を「読んだ 600 から」書き込みます。', 'B の UPDATE は A の行ロックでブロックします。「ロック待ちを確認しました」のメッセージを待ってから A を COMMIT します。', '最後の A の復元 UPDATE で 600 に戻して実験を終えます。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN;', expect: 'ok', note: 'A: トランザクション開始。' },
        { session: 'B', sql: 'BEGIN;', expect: 'ok', note: 'B: 同時に開始。' },
        { session: 'A', sql: 'SELECT price FROM public.books WHERE book_id = 1;', expect: 'ok', note: 'A: 600 を読みます。' },
        { session: 'B', sql: 'SELECT price FROM public.books WHERE book_id = 1;', expect: 'ok', note: 'B: 同じく 600 を読みます。' },
        { session: 'A', sql: 'UPDATE public.books SET price = 800 WHERE book_id = 1;', expect: 'ok', note: 'A: 600 + 200 として 800 を書きます（行ロックを握る）。' },
        { session: 'B', sql: 'UPDATE public.books SET price = 700 WHERE book_id = 1;', expect: 'blocks', note: 'B: A の行ロック待ちでブロック。メッセージを確認したら次へ。' },
        { session: 'A', sql: 'COMMIT;', expect: 'ok', note: 'A: 確定。B の待っていた更新が通ります。' },
        { session: 'B', sql: 'SELECT price FROM public.books WHERE book_id = 1;', expect: 'ok', note: 'B: 結果は 700。A の 800 は上書きで消えました（ロストアップデート）。' },
        { session: 'B', sql: 'ROLLBACK;', expect: 'ok', note: 'B: 実験を取り消します（700 が消え、現在の値は A の 800 です）。' },
        { session: 'A', sql: 'UPDATE public.books SET price = 500 + book_id * 100 WHERE book_id = 1;', expect: 'ok', note: 'A: seed の正規形（600）に復元します。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL（InnoDB）は READ COMMITTED / REPEATABLE READ とも、更新の際は**現在読み（最新版を読み直す）**で進めるため、この黙って上書きの現象は同じように起きます。InnoDB が REPEATABLE READ でも更新時に上書きを許す点は PostgreSQL の RR（拒否する）と逆で、前ステップの mysqlNote の通りです。どのデータベースでも「読んだ値を素に書く」コードは禁じ手、が実務の結論です。' },
    { id: 'ch09-08', title: 'SELECT ... FOR UPDATE — 先にロックして読む、の解決策', session: 'AB',
      story: '前のステップの「失われた更新」を、待たせる側と待たされる側がはっきり分かる形で解決します。読み取りに「この行は私が変えます」という札を付けるのです。',
      explanation: '## 読み取りながら行ロックを取る\n```sql\nSELECT price FROM public.books WHERE book_id = 1 FOR UPDATE;\n```\n`FOR UPDATE` を付けた SELECT は、**読んだ行のロックを即座に取得**します。ロックが取れるまで（他のトランザクションが握っていたら）**待たされます**。\n\n前のステップとの違いを、ガイドで観察してください:\n1. **A** が FOR UPDATE で読む（=ロックを握る）\n2. **B** が FOR UPDATE で読もうとして、**ブロック**される\n3. **A** が 800 に更新して COMMIT（ロック解放）\n4. **B** の読み取りが解放され、見えるのは **最新の 800**。B は「600 だと思って進めていた」計画を、ここで捨てて**最新値に基づいて** 900 を書く\n\nつまり FOR UPDATE は「**読み取った値が、書き込むまで誰にも変えさせない**」を保証します。ロストアップデートの原因は「古い値で判断すること」だったので、判断の時点でロックを取れば原理的に消えます。\n\n注意点:\n- FOR UPDATE は**悲観的ロック**。「使う人がいるかもしれないから先に押さえる」方式で、競合が頻繁なら待ち行列ができます\n- 取る順序が揃っていないと、2つのトランザクションが互いを待つ**デッドロック**が起き得ます（この章の最後のステップで実演します）\n- 読むだけなら `FOR SHARE`（共有ロック）で十分な場合もあります\n\n**なぜ実務でこうするか**: 「この行を今から変える」という意思表示は、在庫引き当てや口座振替のような「行を1行に絞った業務」で最も簡単で確実な解です。対象が1行（蔵書や商品）に特定できる業務は、FOR UPDATE が第一候補になります。',
      task: 'ガイドに沿って: A が FOR UPDATE で読む → B が FOR UPDATE で読む（ブロック）→ A が 800 に更新して COMMIT → B が 800 を見て 900 に更新 → B COMMIT → B が復元。',
      hints: ['SELECT price FROM public.books WHERE book_id = 1 FOR UPDATE; — 行ロックつきの読み取りです。', 'B の FOR UPDATE は A の COMMIT までブロックします。解放されたら結果は 800 です。', 'B は最新値 800 を基準に price + 100（→900）を書きます（相対更新）。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN;', expect: 'ok', note: 'A: トランザクション開始。' },
        { session: 'A', sql: 'SELECT price FROM public.books WHERE book_id = 1 FOR UPDATE;', expect: 'ok', note: 'A: 読みながら行ロックを取得（600）。' },
        { session: 'B', sql: 'BEGIN;', expect: 'ok', note: 'B: トランザクション開始。' },
        { session: 'B', sql: 'SELECT price FROM public.books WHERE book_id = 1 FOR UPDATE;', expect: 'blocks', note: 'B: A のロック待ちでブロック。メッセージを確認したら次へ。' },
        { session: 'A', sql: 'UPDATE public.books SET price = price + 200 WHERE book_id = 1;', expect: 'ok', note: 'A: 読んだ値に基づいて 800 に更新します。' },
        { session: 'A', sql: 'COMMIT;', expect: 'ok', note: 'A: 確定してロックを解放。B の読み取りが通ります。' },
        { session: 'B', sql: 'UPDATE public.books SET price = price + 100 WHERE book_id = 1;', expect: 'ok', note: 'B: 解放後の最新値 800 を基準に 900 に更新します（ロストアップデート無し）。' },
        { session: 'B', sql: 'COMMIT;', expect: 'ok', note: 'B: 確定。両者の更新がどちらも生きています。' },
        { session: 'B', sql: 'UPDATE public.books SET price = 500 + book_id * 100 WHERE book_id = 1;', expect: 'ok', note: 'B: seed の正規形（600）に復元します。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL でも `SELECT ... FOR UPDATE` は同じ構文・同じ意味です（InnoDB の行ロック）。MySQL 8.0 からは `FOR UPDATE NOWAIT` / `SKIP LOCKED` も使えます（PostgreSQL 9.5+ 由来の機能が逆輸入された形）。ジョブキューの実装（先頭1行を取る）で使う `FOR UPDATE SKIP LOCKED` は、両データベースで定番になっています。' },
    { id: 'ch09-09', title: '同じ蔵書の同時貸出 — トリガーと一意索引の二重防御', session: 'AB',
      story: '7章で作った貸出トリガーの、本来の晴れ舞台です。「同じ本を2つの窓口が同時に貸し出そうとしたら？」。FOR UPDATE の行ロックと、2章の一意索引がどう連携するかを見ます。',
      explanation: '## 同時貸出が起きた瞬間の内部\n蔵書5（available）を2つの窓口が同時に貸し出すシナリオ（ガイドどおり）:\n1. **A** が INSERT（貸出 ID 101、蔵書5）→ トリガーが蔵書5の行を **FOR UPDATE でロック**し、status を loaned に変える\n2. **B** も INSERT（貸出 ID 102、同じ蔵書5）→ トリガーは蔵書5のロックを取ろうとして、**A のロック待ちでブロック**\n3. **A** が COMMIT → 貸出確定、蔵書5は loaned のまま\n4. **B** の待っていたトリガーが再開 → status は **loaned** → **23514** で拒否！\n5. **B** は ROLLBACK して窓口で「貸出中です」と案内する\n\n7章の `FOR UPDATE` は、まさにこの瞬間のためにありました。ロックのおかげで「2つの窓口が同時に available を読んで、両方貸してしまう」が**構造的に起きません**。\n\nそして **仮にトリガーがなかったら**: 2章で作った部分一意索引 loans_one_open_copy_idx（未返却の貸出は蔵書ごとに1件まで）が、B の INSERT を **23505** で拒否します。この教材の設計:\n- トリガー = 業務らしいエラーと蔵書状態の維持\n- 一意索引 = 経路を問わない物理的な最終防衛線\n\n**なぜ実務でこうするか**: 「同時に起きないはず」は同時に起きます。窓口が2台ある時点で、二重貸出は現実のシナリオです。チェックをアプリに書くだけで済ませると、将来のバッチ処理や別アプリが穴を開けます。データベース側の二重防御は、誰が侵入しても同じ結果を保証します。',
      task: 'ガイドに沿って: A が蔵書5を貸出 → B が同じ蔵書5を貸出（ブロック）→ A COMMIT → B の INSERT が 23514 で拒否 → B ROLLBACK → A が復元 → B が蔵書状態を確認。',
      hints: ['A: INSERT INTO public.loans (loan_id, copy_id, member_id, due_on) VALUES (101, 5, 1, CURRENT_DATE + 14); です。', 'B の INSERT（ID 102、蔵書5）は A の COMMIT までブロックし、その後 23514 で拒否されます。', '最後に A が貸出 ID 101 を削除して蔵書5を available に戻し、B がそれを確認します。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN;', expect: 'ok', note: 'A: 窓口1のトランザクションです。' },
        { session: 'A', sql: 'INSERT INTO public.loans (loan_id, copy_id, member_id, due_on) VALUES (101, 5, 1, CURRENT_DATE + 14);', expect: 'ok', note: 'A: 蔵書5を貸出。トリガーが蔵書5を行ロックして loaned にします。' },
        { session: 'B', sql: 'BEGIN;', expect: 'ok', note: 'B: 窓口2のトランザクションです。' },
        { session: 'B', sql: 'INSERT INTO public.loans (loan_id, copy_id, member_id, due_on) VALUES (102, 5, 2, CURRENT_DATE + 14);', expect: 'blocks', completionErrorCode: '23514', note: 'B: 同じ蔵書5を貸し出そうとしてブロック。メッセージを確認したら次へ。' },
        { session: 'A', sql: 'COMMIT;', expect: 'ok', note: 'A: 貸出を確定。B の INSERT はトリガーに 23514 で拒否されます。' },
        { session: 'B', sql: 'ROLLBACK;', expect: 'ok', note: 'B: 拒否されたトランザクションを閉じます。' },
        { session: 'A', sql: "BEGIN; DELETE FROM public.loans WHERE loan_id = 101; UPDATE public.copies SET status = 'available' WHERE copy_id = 5 AND status = 'loaned'; COMMIT;", expect: 'ok', note: 'A: 実験の貸出を復元し、蔵書5を available に戻します。' },
        { session: 'B', sql: 'SELECT (SELECT status FROM public.copies WHERE copy_id = 5) AS copy_status;', expect: 'ok', note: 'B: 蔵書5が available に戻ったことを確認します。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL でもトリガー内の SELECT ... FOR UPDATE で同じ防御が作れます。ただし MySQL は**分離レベルが REPEATABLE READ（既定）だと、ロック待ち解除後の読み取りがスナップショットの一貫読みになる**場合があり、更新用の現在読み（FOR UPDATE）と組み合わせる設計が重要です。一意索引による最終防衛線は、MySQL の UNIQUE KEY でも同じ形で作れます（部分索引が無いため、未返却を表す生成列などの工夫が必要 — 2章の mysqlNote 参照）。' },
    { id: 'ch09-10', title: 'NOWAIT と lock_timeout — 無限の待ちに、出口を作る', session: 'AB',
      story: 'ここまで「ロック待ちは解放されるまで待つ」を見てきました。でも相手が COMMIT を忘れたまま昼食に行ったら？ 待つ側にも、諦める選択肢が必要です。',
      explanation: '## 待つか、諦めるか、タイムアウトするか\n3つの選択肢（ガイドで両方体験します）:\n\n1. **通常（待つ）** — `FOR UPDATE`。相手が COMMIT/ROLLBACK するまで無期限に待つ\n2. **lock_timeout** — `SET lock_timeout = \'2s\';` を先に実行しておくと、ロック取得を**2秒だけ**待って、諦めてエラー **55P03** になります\n3. **NOWAIT** — `FOR UPDATE NOWAIT`。待たずに即座に 55P03。待つ価値が無いと分かっている場面向け\n\nどちらのエラーも SQLSTATE は **55P03（lock_not_available）**。アプリはこのコードを見て「後でもう一度」の案内やリトライに変換できます。「固まった画面」より、失敗して分かる方がよい場面は多いです。\n\n実務での使い分け:\n- 待ってもよい業務 → 既定（無期限）。ただし lock_timeout を「保険」として秒単位で掛ける現場は多い（障害時のスタック防止）\n- 高頻度で競合する行 → NOWAIT で即失敗させ、少し待ってリトライ（アプリ側でタイミングをずらす）\n- **待つ側の工夫より「待たせる側を短くする」方が効く**——トランザクションを必要最小限に閉じるのが大原則です\n\n**なぜ実務でこうするか**: ロック待ちの連鎖で Web アプリのワーカーが枯渇すると、障害全体が止まります。lock_timeout は「1リクエストの失敗で全体を守る」保険です。\n\n※ B の2つ目の SELECT は待ちを観察するために使います。ガイドの順番（B が「ロック待ちを確認しました」のメッセージを待つ）を守ってください。',
      task: 'ガイドに沿って: A が FOR UPDATE で読む → B が lock_timeout 2秒つきで読む（2秒で 55P03）→ B が NOWAIT で読む（即 55P03）→ A ROLLBACK。',
      hints: ['B の2つ目の SELECT は2秒待った後 55P03 で失敗します（completionErrorCode に注目）。', 'B の3つ目の SELECT は FOR UPDATE NOWAIT で、即座に 55P03 になります。', '最後に A が ROLLBACK してロックを解放します。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN;', expect: 'ok', note: 'A: トランザクションを開始します。' },
        { session: 'A', sql: 'SELECT member_id, name FROM public.members WHERE member_id = 3 FOR UPDATE;', expect: 'ok', note: 'A: 会員3の行ロックを取得します。' },
        { session: 'B', sql: "SET lock_timeout = '2s';", expect: 'ok', note: 'B: このセッションで、ロック待ちを2秒で打ち切る設定にします。' },
        { session: 'B', sql: 'SELECT member_id, name FROM public.members WHERE member_id = 3 FOR UPDATE;', expect: 'blocks', completionErrorCode: '55P03', note: 'B: 2秒待っても取れないので 55P03 で諦めます（メッセージを待ってから次へ）。' },
        { session: 'B', sql: 'SET lock_timeout TO DEFAULT;', expect: 'ok', note: 'B: 保険を元に戻します。' },
        { session: 'B', sql: 'SELECT member_id, name FROM public.members WHERE member_id = 3 FOR UPDATE NOWAIT;', expect: { errorCode: '55P03' }, note: 'B: NOWAIT なら待たずに即座に 55P03 です。' },
        { session: 'A', sql: 'ROLLBACK;', expect: 'ok', note: 'A: ロックを解放して実験を終えます。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL には lock_timeout に相当する **innodb_lock_wait_timeout**（既定50秒）があり、時間切れは ERROR 1205（SQLSTATE HY000）です。NOWAIT / SKIP LOCKED は MySQL 8.0 以降 `FOR UPDATE NOWAIT` として使えます。エラー番号・SQLSTATE の体系が違う（PostgreSQL は 55P03 に統一）ので、リトライ処理は DB ごとに書くことになります。' },
    { id: 'ch09-11', title: 'デッドロック — 待ち合わせの循環と 40P01', session: 'AB',
      story: '最後の仕上げは、ロックの世界で一番怖い現象です。A が B のロックを待ち、B が A のロックを待つ。どちらも相手が解放するのを待つまま、永遠に進めません。',
      explanation: '## デッドロックは検出される\nガイドのシナリオ（会員1と会員2の2行を使います）:\n1. **A** が会員1を更新（会員1のロックを握る）\n2. **B** が会員2を更新（会員2のロックを握る）\n3. **B** が会員1を更新しようとして**ブロック**（A が握っている）\n4. **A** が会員2を更新しようとする → ここで**待ちの循環が完成**（A→B→A）→ A は **40P01** で中止されます\n\nPostgreSQL はロックの**待ちグラフ**を巡回して循環を検出し、**片方だけ**を中止させます。検出のきっかけは `deadlock_timeout`（既定1秒）で、**待ち始めてからこの時間を超えると検査が走ります**。\n\n今回の実験で A と B に `SET deadlock_timeout` で異なる値を設定しているのは、**どちらが犠牲になるかをこの演習用に固定するため**です。A は「後から待ち始めた」側なので、検出タイマーを10ms にすると、A は自分が待ち始めた直後（＝循環が完成した直後）に必ず検査を実行して、自分が循環にいることを発見します。B のタイマーは十分長くし、B は検査を実行しないようにします。本番でこの設定を変えることはあまりありません。\n\n中止のされ方に注意:\n- 中止されるのは**そのステートメント**だけです。トランザクションは failed 状態で**ロックを持ったまま**残ります（だからガイドでは、犠牲になった A が ROLLBACK して解放します）\n- 犠牲になったアプリの正しい反応は**トランザクション全体のやり直し**です\n\n予防法（実務の本命）:\n- **更新順序を揃える**。全コードが「会員IDの昇順」など同じ順で行ロックを取れば、循環は原理的に成立しません\n- 1トランザクションで掴む行数を減らす、時間を短くする\n- どうしても防げないなら、40P01 を「起こり得る失敗」としてリトライで包む\n\n**なぜ実務でこうするか**: デッドロックは「設計が悪い」というより「順序の約束が無い」ことで起きます。テーブルアクセスの順序を規約化するだけで、夜間バッチの相性事故は激減します。',
      task: 'ガイドに沿って: deadlock_timeout を設定 → A・B が互い違いに行を更新 → B がブロックし、循環完成後に A が 40P01 で中止される → A が ROLLBACK で解放 → B ROLLBACK → 設定を戻す。',
      hints: ['最初に A と B の両方で deadlock_timeout を設定します（A は 10ms、B は 60秒。犠牲者を A に固定する工夫です）。', 'B の2回目の更新（会員1）がブロックします。「ロック待ちを確認しました」のメッセージを待ってから A の2回目の更新（会員2）を実行します。', 'A の2回目の更新は 40P01（デッドロック検出）で失敗します。その後 A が ROLLBACK でロックを手放します。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: "SET deadlock_timeout = '10ms';", expect: 'ok', note: 'A: 待ち開始から直ぐに検査が走るようにします（犠牲者を A に固定する工夫）。' },
        { session: 'B', sql: "SET deadlock_timeout = '60s';", expect: 'ok', note: 'B: 検査が走らないように、タイマーを十二分に長くします。' },
        { session: 'A', sql: 'BEGIN;', expect: 'ok', note: 'A: トランザクション開始。' },
        { session: 'A', sql: 'UPDATE public.members SET name = name WHERE member_id = 1;', expect: 'ok', note: 'A: 会員1の行ロックを取得（値は変えません）。' },
        { session: 'B', sql: 'BEGIN;', expect: 'ok', note: 'B: トランザクション開始。' },
        { session: 'B', sql: 'UPDATE public.members SET name = name WHERE member_id = 2;', expect: 'ok', note: 'B: 会員2の行ロックを取得。' },
        { session: 'B', sql: 'UPDATE public.members SET name = name WHERE member_id = 1;', expect: 'blocks', note: 'B: 会員1は A が握っているのでブロックします。メッセージを待って次へ。' },
        { session: 'A', sql: 'UPDATE public.members SET name = name WHERE member_id = 2;', expect: { errorCode: '40P01' }, note: 'A: 会員2は B が握っているので待ち始め、直後に循環を検出。A が 40P01 で中止されます（デッドロックの犠牲者）。' },
        { session: 'A', sql: 'ROLLBACK;', expect: 'ok', note: 'A: （中止された後）ロックを手放します。B の待っていた更新が通り始めます。' },
        { session: 'B', sql: 'ROLLBACK;', expect: 'ok', note: 'B: 実験を終了します。' },
        { session: 'A', sql: 'SET deadlock_timeout TO DEFAULT;', expect: 'ok', note: 'A: 演習用の設定を戻します。' },
        { session: 'B', sql: 'SET deadlock_timeout TO DEFAULT;', expect: 'ok', note: 'B: 同様に戻します。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL（InnoDB）はデッドロックを**即座**に検出します（待ちグラフの巡回を待たず、ロック取得のたびに検査。innodb_deadlock_detect=ON が既定）。犠牲者は ERROR 1213（SQLSTATE 40001）です。PostgreSQL は deadlock_timeout の時間を待ってから検査する（即時検出のコストが高いと判断）点が違いです。「順序を揃えて予防」が最良の解であることは、両方で変わりません。' },
  ],
}
export default chapter
