import type { Chapter } from '../src/shared/lessons.js'
const chapter: Chapter = {
  id: 12, title: '総合演習', summary: '「予約機能を追加せよ」— 設計・DDL・索引・権限・トランザクションまで自力で完成させます。',
  steps: [
    { id: 'ch12-01', title: '要件を整理する — 予約機能とは', session: 'A',
      story: '開館1周年の言葉が見えてきました。館長から待望の要望書が届きます。「人気の本が貸出中で取れない、と会員から不満が来ている。予約（取り置きの順番待ち）機能を追加してくれ」。最終章では、ここまで学んだすべて — 設計・DDL・索引・権限・トランザクション — を自分で組み合わせて、この機能を作り切ります。',
      explanation: `## 要件を「表」の言葉に訳す\n要望書の一文を、システムの言葉に訳し直します。\n\n1. **「予約」は何に対するか** — 会員が待ちたいのは「この本」であって「この物理的な1冊」ではない（別の返却された冊数でも良いから）。つまり reservations が参照するのは **books（書誌）** であって copies（蔵書）ではない。2章で books と copies を分けた理由が、ここで回収されます。\n2. **誰が・いつ並んだか** — member_id（誰が）、reserved_at（いつ）。先着順が必要なので reserved_at は自動記録（既定 CURRENT_TIMESTAMP）。\n3. **状態は3つ** — pending（順番待ち）→ fulfilled（貸出に変換した）or cancelled（取り消した）。2章の copies.status と同じ「text + CHECK」パターン。\n4. **同じ会員が同じ本を2回並ばない** — 「pending の間だけ」一意。これが1つの業務ルール。\n5. **予約の記録は消さない** — 取り消しても行は残す（会員の行動履歴）。members/books への FK は RESTRICT。\n6. **予約を入れるのは** — アプリ（会員の操作）と司書（窓口対応）。閲覧者は不可。\n\n## この章の規範\n\`lessons/data/reservations.sql\` が**完成形の規範**です（契約）。ただしこの章の目的は「写すこと」ではなく「この形に自分で到達すること」です。各ステップで要件の一部を渡し、あなたが SQL を書きます。\n\n| 要件 | 実装するもの | ステップ |\n|---|---|---|\n| 1〜3, 5 | reservations 表（5列・制約つき） | 02 |\n| 4 | pending だけの部分一意索引 + 待ち行列索引 | 03 |\n| 6 | lib_librarian / lib_app への権限 | 04 |\n| 二重予約の安全確認 | 2セッションでの同時予約実験 | 05 |\n| アプリの視点 | lib_app で予約を体験 | 06 |\n\n## なぜ実務でこうするか\n実務の機能追加は「コードを書く」前にこの表を作ることから始まります。この一覧が仕様書とDDLの対応表になり、レビュー（と後の自分）が要件を追跡できます。「この索引はどの要件のため?」にすぐ答えられる設計だけが、1年後に安全に変更できる設計です。`,
      task: '要件1〜6と実装の対応を確認してください。この章で作るもの全体像を掴んだら「読みました・次へ進む準備」を押します。',
      hints: ['「予約の対象は books（書誌）であって copies（1冊）ではない」点が、2章の正規化の回収です（要件1）。', '「同じ会員が同じ本を2重に並ばない」は pending の間だけの一意性なので、WHERE つき部分一意インデックスで強制します（要件4 → ステップ03）。', '予約を書くのは司書とアプリだけで、取消は行削除ではなく status の UPDATE で表現します（要件5・6 → ステップ04）。'],
      solution: '',
      replay: '',
      check: { type: 'manual' },
      mysqlNote: '要件定義・設計の進め方は MySQL でも全く同じです。以降のステップで、実装の差（部分インデックスの有無・権限の単位・トランザクション）が MySQL 側の対応策とどう違うかを都度示します。' },
    { id: 'ch12-02', title: 'reservations 表を作る', session: 'A',
      story: 'それでは設計をDDLに落とします。要件1〜3・5を1枚の CREATE TABLE に。2章の型・制約の作法と7章以降の知識を全部使います。',
      explanation: `## 列と制約の設計判断\n| 列 | 型・制約 | 理由 |\n|---|---|---|\n| reservation_id | integer IDENTITY BY DEFAULT + PK | 予約の身分証。自動採番 |\n| book_id | integer NOT NULL + FK → books（RESTRICT） | 予約対象は**書誌**（要件1） |\n| member_id | integer NOT NULL + FK → members（RESTRICT） | 並んだ会員 |\n| reserved_at | timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP | 先着順の記録。自動記録（要件2） |\n| status | text NOT NULL DEFAULT 'pending' + CHECK | pending/fulfilled/cancelled（要件3） |\n\n- **CHECK (status IN ('pending','fulfilled','cancelled'))** — 2章と同じ固定値パターン。\n- **FK は RESTRICT** — 予約の記録は消さない（要件5）。会員や書誌を削除して予約が黙って消えることは許さない。\n- NOT NULL には名前を付けます（2章の作法。PK による予約IDの NOT NULL は PG の暗黙命名に任せます）。\n\n## なぜ実務でこうするか\n「予約って消さないの?」は業務の根幹の質問です。取り消し（cancelled）も履歴として残す設計は、後から「あの会員は予約を何回取り消したか」という問いに答えられます。物理削除してよいデータは、実務には意外と少ない、というのが正しい感覚です。\n\n模範解答は reservations.sql の規範どおりです。制約名まで同じにしてください（後の指紋比較と、誰かが読むときの手がかりになります）。`,
      task: 'reservations 表を規範（reservations.sql）どおりに作成してください。5列・名前つきNOT NULL・CHECK・2つの外部キー（RESTRICT）まで完全に。',
      hints: ['骨格は CREATE TABLE public.reservations ( ... ); です。ID 列は integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT reservations_pkey PRIMARY KEY。', "reserved_at は timestamptz DEFAULT CURRENT_TIMESTAMP CONSTRAINT reservations_reserved_at_nn NOT NULL、status は text DEFAULT 'pending' CONSTRAINT reservations_status_nn NOT NULL。", "CHECK は CONSTRAINT reservations_status_check CHECK (status IN ('pending', 'fulfilled', 'cancelled'))。FK は reservations_book_id_fkey / reservations_member_id_fkey で、どちらも ON DELETE RESTRICT です。"],
      solution: `CREATE TABLE public.reservations (
  reservation_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT reservations_pkey PRIMARY KEY,
  book_id integer CONSTRAINT reservations_book_id_nn NOT NULL,
  member_id integer CONSTRAINT reservations_member_id_nn NOT NULL,
  reserved_at timestamptz DEFAULT CURRENT_TIMESTAMP CONSTRAINT reservations_reserved_at_nn NOT NULL,
  status text DEFAULT 'pending' CONSTRAINT reservations_status_nn NOT NULL,
  CONSTRAINT reservations_status_check CHECK (status IN ('pending', 'fulfilled', 'cancelled')),
  CONSTRAINT reservations_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.books(book_id) ON DELETE RESTRICT,
  CONSTRAINT reservations_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(member_id) ON DELETE RESTRICT
);`,
      check: { type: 'sql', sql: `SELECT to_regclass('public.reservations') IS NOT NULL
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'reservations') = 5
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'reservations'
    AND column_name = 'reservation_id' AND data_type = 'integer' AND is_nullable = 'NO'
    AND is_identity = 'YES' AND identity_generation = 'BY DEFAULT') = 1
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'reservations'
    AND column_name IN ('book_id', 'member_id') AND data_type = 'integer' AND is_nullable = 'NO' AND is_identity = 'NO') = 2
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'reservations'
    AND column_name = 'reserved_at' AND data_type = 'timestamp with time zone' AND is_nullable = 'NO'
    AND column_default = 'CURRENT_TIMESTAMP') = 1
  AND (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'reservations'
    AND column_name = 'status' AND data_type = 'text' AND is_nullable = 'NO'
    AND column_default = '''pending''::text') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = 'public.reservations'::regclass
    AND contype = 'p' AND conname = 'reservations_pkey') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = 'public.reservations'::regclass
    AND contype = 'c' AND conname = 'reservations_status_check'
    AND pg_get_constraintdef(oid) LIKE '%pending%' AND pg_get_constraintdef(oid) LIKE '%fulfilled%'
    AND pg_get_constraintdef(oid) LIKE '%cancelled%') = 1
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = 'public.reservations'::regclass
    AND contype = 'f' AND conname IN ('reservations_book_id_fkey', 'reservations_member_id_fkey')
    AND pg_get_constraintdef(oid) LIKE '%ON DELETE RESTRICT%') = 2
  AND (SELECT count(*) FROM pg_constraint WHERE conrelid = 'public.reservations'::regclass
    AND contype = 'n' AND conname IN ('reservations_book_id_nn', 'reservations_member_id_nn',
      'reservations_reserved_at_nn', 'reservations_status_nn')) = 4` },
      mysqlNote: 'MySQL でも同じ CREATE TABLE が書けます（INT AUTO_INCREMENT PRIMARY KEY、CHECK は 8.0.16 以降で実効、FK は InnoDB で RESTRICT）。timestamptz が無い点だけ 2章のとおり DATETIME で UTC 運用にします。ON DELETE の選択肢・CHECK・複数列の NOT NULL の考え方はそのまま移植できます。' },
    { id: 'ch12-03', title: '二重予約を防ぐ2つの部分インデックス', session: 'A',
      story: '表はできました。次は「同じ会員が同じ本を pending で2回並ばない」（要件4）と「先着順の待ち行列」を、データベース自身が守る仕組みにします。2章の loans_one_open_copy_idx と同じ技術の応用です。',
      explanation: `## 業務ルールは索引で機械的に守る\n**要件4「同じ (book_id, member_id) の pending は高々1行」** — これは表や主キーでは表現できない「状態つきの一意性」です。2章の「未返却の貸出は1冊1件」と同じく、**部分一意インデックス**で強制します:\n\n\`\`\`sql\nCREATE UNIQUE INDEX reservations_one_pending_idx\n  ON public.reservations(book_id, member_id) WHERE status = 'pending';\n\`\`\`\n\nWHERE で「pending の行だけ」に範囲を絞って一意性を強制するので、**過去の fulfilled / cancelled は何度重なってもよい**（同じ会員が取り消してもう1度並び直せる）のに、並んでいる間の二重予約は 23505 で機械的に拒否できます。\n\n**「次に誰に貸すか」を即座に引く索引** — 待ち行列の先頭は「book_id ごとに reserved_at の若い順」です。\n\n\`\`\`sql\nCREATE INDEX reservations_queue_idx\n  ON public.reservations(book_id, reserved_at) WHERE status = 'pending';\n\`\`\`\n\nこれは一意ではない通常の索引で、「この本の次の1人」を \`ORDER BY reserved_at LIMIT 1\` で索引だけで解決させるためのものです。\n\n## なぜ実務でこうするか\n「アプリで二重予約をチェックしてから INSERT」だけだと、**同時に走った2つのリクエストが両方チェックを通過**して二重予約が成立します（9章で体験した競合そのもの）。一意索引なら同時実行でも必ず片方だけが成功します（05のステップで体験します）。また索引は検索の高速化と**制約の強制**を兼ねるので、「何のための索引か」を制約名・コメントに残すのが実務の作法です。`,
      task: '2つの部分インデックス（reservations_one_pending_idx / reservations_queue_idx）を規範どおりに作成してください。',
      hints: ['CREATE UNIQUE INDEX reservations_one_pending_idx ON public.reservations(book_id, member_id) WHERE status = \'pending\'; が1つ目です。', '2つ目は CREATE INDEX reservations_queue_idx ON public.reservations(book_id, reserved_at) WHERE status = \'pending\';（UNIQUE なし）。', "どちらも WHERE status = 'pending' の部分索引です。"],
      solution: `CREATE UNIQUE INDEX reservations_one_pending_idx
  ON public.reservations(book_id, member_id) WHERE status = 'pending';
CREATE INDEX reservations_queue_idx
  ON public.reservations(book_id, reserved_at) WHERE status = 'pending';`,
      check: { type: 'sql', sql: `SELECT (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'reservations'
    AND indexname = 'reservations_one_pending_idx' AND indexdef LIKE '%UNIQUE%'
    AND indexdef LIKE '%(book_id, member_id)%' AND indexdef LIKE '%WHERE (status = ''pending''::text)%') = 1
  AND (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'reservations'
    AND indexname = 'reservations_queue_idx' AND indexdef NOT LIKE '%UNIQUE%'
    AND indexdef LIKE '%(book_id, reserved_at)%' AND indexdef LIKE '%WHERE (status = ''pending''::text)%') = 1
  AND (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'reservations') = 3` },
      mysqlNote: `MySQL に部分インデックスは無いので（2章のとおり）生成列での代替が定番です: \`is_open INT GENERATED ALWAYS AS (IF(status='pending',1,NULL)) STORED\`（または book_id と member_id の組を pending のときだけ非NULLにする列）を足して \`UNIQUE KEY (book_id, member_id, is_open)\` とします。NULL は一意制約に引っかからない性質を利用します。PostgreSQL のように「WHERE つき一意」を1文で書けないぶん、列設計に載せる必要がある、という差が移行時の要点です。` },
    { id: 'ch12-04', title: '予約を司書とアプリに委譲する', session: 'A',
      story: '表と索引ができました。ここで10章の仕掛けが効いてきます。実は…司書グループはもう reservations を使えるはずです。確かめてから、残りの権限を契約どおり与えます。',
      explanation: `## まず現状を確認する\n作ってみましょう:\n\n\`\`\`sql\nSELECT has_table_privilege('lib_librarian', 'public.reservations', 'INSERT') AS librarian_insert,\n       has_table_privilege('lib_reader', 'public.reservations', 'SELECT') AS reader_select;\n\`\`\`\n\n**true が返るはずです**。reservations は dojo_learner が public スキーマに作ったので、10章で設定した **ALTER DEFAULT PRIVILEGES**（dojo_learner が作る表には lib_librarian に SELECT/INSERT/UPDATE、lib_reader に SELECT）が、CREATE TABLE の瞬間に自動で効いたのです。「来月の表を忘れずに権限付けする」事故を防ぐ仕掛けが、まさに今働きました。\n\n## 残る仕事と、明示の意味\n契約（要件6）では lib_librarian と lib_app の**両方**に明示的に与えることになっています:\n\n\`\`\`sql\nGRANT SELECT, INSERT, UPDATE ON public.reservations TO lib_librarian, lib_app;\nGRANT USAGE, SELECT ON SEQUENCE public.reservations_reservation_id_seq TO lib_librarian, lib_app;\n\`\`\`\n\n- lib_librarian への表権限は既定権限と重複しますが、**意図を明示する**（この表は誰が使う表かをSQLで読める）意味があり、害はありません。\n- lib_app は既定権限の対象外（10章の設計）なので、ここが必須の付与です。シーケンスは USAGE/SELECT を付けます（IDENTITY の内部採番は所有者権限で評価されるので INSERT だけなら USAGE が無くても通りますが、10章の契約として明示し、nextval を直接使えるようにします）。\n- **DELETE は与えません**。予約の取消は status を cancelled にする UPDATE で表現するため（行は消さない = 要件5）。削除したい誘惑に権限レベルで蓋をするのが10章の作法でした。\n\n## なぜ実務でこうするか\n「既定権限があるから大丈夫」と**過信しない**ことも実務の作法です。既定は「作った人」に紐づく（FOR ROLE）ので、別の管理者が作った表には効きません。だから重要な表は、このステップのように**明示的な GRANT で契約をSQLに書く**。既定は網、明示は契約書、と役割分担させます。`,
      task: 'reservations への SELECT/INSERT/UPDATE を lib_librarian と lib_app に、シーケンス reservations_reservation_id_seq への USAGE/SELECT を両者に与えてください（DELETE は与えません）。',
      hints: ['まず has_table_privilege で司書が既に使えることを確認します（既定権限の効果）。', 'GRANT SELECT, INSERT, UPDATE ON public.reservations TO lib_librarian, lib_app; が表への付与です。', 'GRANT USAGE, SELECT ON SEQUENCE public.reservations_reservation_id_seq TO lib_librarian, lib_app; が採番への付与です。'],
      solution: `GRANT SELECT, INSERT, UPDATE ON public.reservations TO lib_librarian, lib_app;
GRANT USAGE, SELECT ON SEQUENCE public.reservations_reservation_id_seq TO lib_librarian, lib_app;`,
      check: { type: 'sql', sql: `SELECT has_table_privilege('lib_librarian', 'public.reservations', 'SELECT')
  AND has_table_privilege('lib_librarian', 'public.reservations', 'INSERT')
  AND has_table_privilege('lib_librarian', 'public.reservations', 'UPDATE')
  AND NOT has_table_privilege('lib_librarian', 'public.reservations', 'DELETE')
  AND has_table_privilege('lib_app', 'public.reservations', 'SELECT')
  AND has_table_privilege('lib_app', 'public.reservations', 'INSERT')
  AND has_table_privilege('lib_app', 'public.reservations', 'UPDATE')
  AND NOT has_table_privilege('lib_app', 'public.reservations', 'DELETE')
  AND has_sequence_privilege('lib_librarian', 'public.reservations_reservation_id_seq', 'USAGE')
  AND has_sequence_privilege('lib_librarian', 'public.reservations_reservation_id_seq', 'SELECT')
  AND has_sequence_privilege('lib_app', 'public.reservations_reservation_id_seq', 'USAGE')
  AND has_sequence_privilege('lib_app', 'public.reservations_reservation_id_seq', 'SELECT')
  AND NOT has_table_privilege('lib_reader', 'public.reservations', 'INSERT')
  AND NOT has_table_privilege('lib_sato', 'public.reservations', 'INSERT')` },
      mysqlNote: 'MySQL なら `GRANT SELECT, INSERT, UPDATE ON library.reservations TO \'lib_librarian\'@\'%\', \'lib_app\'@\'%\';` です（複数被付与者を1文に書ける点は PG と同じ）。シーケンスが存在しないので採番への追加権限は不要（AUTO_INCREMENT）。PG の「既定権限」に相当するのは ON library.* 付与で、ここでも「DB単位の付与と表単位の明示の使い分け」という同じ考え方が通じます。' },
    { id: 'ch12-05', title: '同時予約を、UNIQUE とトランザクションで守る', session: 'AB',
      connect: { A: { user: 'admin', password: '', database: 'library' }, B: { user: 'admin', password: '', database: 'library' } },
      story: 'いちばん怖いのは「同じ本に同じ会員の予約が、タイミングが重なって2つ入る」ことです。9章で学んだ競合の知識と、今作った部分一意索引の合わせ技を、セッション A / B の2人同時実行で試します。',
      explanation: `## 何が起きるか\nガイドの順番:\n1. **A**: BEGIN して、book_id=1 / member_id=1 の予約を INSERT（まだ COMMIT しない）\n2. **B**: BEGIN して、**同じ (book_id, member_id, status=pending)** を INSERT しようとする\n3. → **B は待たされます**。一意索引の挿入は、A の未コミット行と衝突する可能性があるため、A の結論（COMMIT か ROLLBACK か）を待つのです（speculative insertion 待ち）\n4. **A**: ROLLBACK（A が取り消した）→ **B の待ちは解け、B の INSERT が成功する**\n5. **B**: SELECT で自分の予約が1行見える\n6. **B**: ROLLBACK（演習なので取り消す。表は0行のまま）\n\nもし A が COMMIT していたら、B には **23505（duplicate key value violates unique constraint "reservations_one_pending_idx"）** が返ります。つまり:\n- **どちらの順番で終わっても、pending の重複は1行も作られない**\n- 失敗した側はクライアントコードで「既に予約済みです」と案内すればよい（エラーコードで分岐できる）\n\n## なぜ実務でこうするか\n「アプリで SELECT して無ければ INSERT」には9章で見たレースがあります。一意索引 + トランザクションなら、**確認を省略して INSERT だけ打ってよい**（fail-fast）になります。実務の予約・注文・在庫引き当ては、ほぼこの構成 — 業務キーの一意索引に INSERT をぶつけて、23505 を「既にある」のシグナルとして扱う — で守ります。\n\nこのステップはガイドに沿って A / B 両方のエディタで実行します（実行の順番までガイドが管理します）。実験は全部取り消すので、表は0行のままです。`,
      task: 'ガイドに沿って A・B 順に実行してください。B の INSERT がロック待ちになること、A の ROLLBACK で待ちが解けて成功すること、最後に両方取り消して reservations が0行になることを確認します。',
      hints: ['A は BEGIN → INSERT → ROLLBACK、B は BEGIN → INSERT（待ち）→ SELECT → ROLLBACK の順です。', 'B の INSERT は A の ROLLBACK まで返ってきません（ガイドの「ロック待ちを観察」）。', 'A が COMMIT する代わりに ROLLBACK するのがこの演習。COMMIT なら B は 23505 になります（説明参照）。'],
      solution: '',
      replay: '',
      script: [
        { session: 'A', sql: 'BEGIN', expect: 'ok', note: 'A（作業用アカウント）が先に予約を開始します。' },
        { session: 'A', sql: 'INSERT INTO public.reservations (book_id, member_id) VALUES (1, 1) RETURNING reservation_id, status', expect: 'ok', note: 'まだコミットしない（この行は A のトランザクションからしか見えません）。' },
        { session: 'B', sql: 'BEGIN', expect: 'ok', note: 'B（もう1つの作業用アカウント）が同じ会員・同じ本を予約しようとします。' },
        { session: 'B', sql: 'INSERT INTO public.reservations (book_id, member_id) VALUES (1, 1)', expect: 'blocks', note: '同じ (book_id, member_id, pending) なので部分一意索引と衝突 → A の結論を待たされます。' },
        { session: 'A', sql: 'ROLLBACK', expect: 'ok', note: 'A が取り消すと、B の INSERT の待ちは自動的に解けます。' },
        { session: 'B', sql: 'SELECT reservation_id, book_id, member_id, status FROM public.reservations', expect: 'ok', note: '待っていた B の INSERT は成功しています。自分のトランザクションから1行見えます。' },
        { session: 'B', sql: 'ROLLBACK', expect: 'ok', note: '演習なので B も取り消します。reservations は0行に戻ります。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'InnoDB の一意索引も同様に、衝突の可能性がある挿入は先行トランザクションの確定を待つ（ロック待ちになる）ので、この挙動自体は MySQL でもほぼ同じです。失敗時に返るエラーは、MySQL では重複キーを表す ERROR 1062（SQLSTATE 23000、Duplicate entry）です（PostgreSQL の 23505 に相当します）。差が出るのは「部分インデックスが無い」点で、MySQL では生成列 + UNIQUE の代替設計（前ステップ）の上でこの実験をすることになります。' },
    { id: 'ch12-06', title: 'アプリで予約を入れる（最小権限のまま）', session: 'B',
      connect: { B: { user: 'lib_app', password: 'lib_app_pw', database: 'library' } },
      story: '最後の動作確認はアプリの口座で。10章では loans への INSERT がトリガーの内部権限に阻まれた lib_app です。予約表はトリガーを持たないので、最小権限のまま書けるはずです。',
      explanation: `## lib_app の予約が通る理由\nch12-04 で lib_app に与えたのは 表の SELECT/INSERT/UPDATE と シーケンスの USAGE/SELECT だけです。予約表には:\n- トリガーが無い（内部で他表の権限が要らない — 10章の loans との違い）\n- IDENTITY の採番は10章で学んだとおり所有者権限で評価される（シーケンスの USAGE も明示してあるので nextval 直叩きでも動く）\n- 外部キー検査（books / members への参照確認）は整合性のため内部で行われるが、この構成で動く\n\nつまり**必要な権限だけできれいに通る**。これが「表を設計する時点で権限も設計する」の実感です。\n\n## 確認すること\nガイドの流れ:\n1. BEGIN（演習なので取り消す前提）\n2. book_id=2 / member_id=2 の予約を INSERT — RETURNING で付いた予約IDと status='pending' を確認\n3. SELECT で自分の行を確認（トランザクションの中）\n4. **同じ (book_id, member_id) をもう一度 INSERT** → ここで **23505**（部分一意索引が業務ルールを強制）\n5. ROLLBACK（表は0行のまま）\n\n23505 が返るのは直前のステップ（12-05）で見たのと同じ「データベースが守る」ので、アプリはこのエラーコードを見て「既に予約済みです」と案内するだけです。`,
      task: 'セッション B を lib_app に切り替え、ガイドに沿って予約を1件入れて確認し、二重予約が 23505 で拒否されることを確認してください（最後は ROLLBACK で表を0行に戻します）。',
      hints: ['「指定の接続に切り替え」で lib_app / lib_app_pw / library に接続します。', 'INSERT INTO public.reservations (book_id, member_id) VALUES (2, 2) RETURNING reservation_id, status; が基本形です。', '同じ INSERT を繰り返すと 23505 になり、ROLLBACK で閉じます。'],
      solution: `BEGIN;
INSERT INTO public.reservations (book_id, member_id) VALUES (2, 2) RETURNING reservation_id, status;
SELECT reservation_id, book_id, member_id, status FROM public.reservations;
INSERT INTO public.reservations (book_id, member_id) VALUES (2, 2);
ROLLBACK;`,
      replay: '',
      script: [
        { session: 'B', sql: 'BEGIN', expect: 'ok', note: 'アプリとして演習します（最後に取り消します）。' },
        { session: 'B', sql: 'INSERT INTO public.reservations (book_id, member_id) VALUES (2, 2) RETURNING reservation_id, status', expect: 'ok', note: '10章で loans の INSERT が阻まれた lib_app でも、予約表はトリガーが無いので与えた権限だけで書けます。' },
        { session: 'B', sql: 'SELECT reservation_id, book_id, member_id, status FROM public.reservations', expect: 'ok', note: '自分のトランザクションの1行が見えます（status は pending）。' },
        { session: 'B', sql: 'INSERT INTO public.reservations (book_id, member_id) VALUES (2, 2)', expect: { errorCode: '23505' }, note: '同じ会員・同じ本の pending は部分一意索引 reservations_one_pending_idx が拒否します。' },
        { session: 'B', sql: 'ROLLBACK', expect: 'ok', note: '演習を取り消します。reservations は0行のままです。' },
      ],
      check: { type: 'script' },
      mysqlNote: 'MySQL でも `INSERT ... ON DUPLICATE KEY UPDATE status = status`（または IGNORE。ただし IGNORE は他のエラーも握り潰すので非推奨）で「二重予約を黙って受け流す」書き方が定番です。PostgreSQL 側はむしろ素直で、部分一意索引を推定する `INSERT INTO public.reservations (book_id, member_id) VALUES (2, 2) ON CONFLICT (book_id, member_id) WHERE status = \'pending\' DO NOTHING;` がそのまま使えます（ON CONFLICT の索引推定は、述語つきの部分索引にも当てはまります）。`ON CONFLICT DO NOTHING ... RETURNING` なら、挿入できたか（行が返るか）まで1文で判定できます。23505 を捕まえてアプリで分岐する書き方と、どちらも実務で使われます。' },
    { id: 'ch12-07', title: '検収して、作業用アカウントに戻る', session: 'B',
      connect: { B: { user: 'admin', password: '', database: 'library' } },
      story: '予約機能の実装が終わりました。引渡しの前に、最終検収クエリで構造・権限・行数を一斉に確認します。そしてアプリ口座を置いたまま帰らない — セッション B を作業用アカウントに戻して、この道場の全課程を締めくくります。',
      explanation: `## 最終検収は1本のクエリで\n実務の引渡しでは「できました」ではなく、**確認できる形**で報告します。構造（制約・索引）と権限と行数を1行でまとめるのがこのステップの検収クエリです（模範解答と同じ列構成で）。\n\n- **row_count = 0** — 演習の予約は全部取り消した（章末状態）\n- **constraints = 4** — 主キー・status CHECK・外部キー2つ\n- **indexes = 3** — 主キー索引・部分一意・待ち行列\n- **writer_roles = 2** — 予約を書けるロール（lib_librarian, lib_app）\n\n## 章末状態とコース全体の到達点\n- reservations 表・2索引・権限・0行\n- A / B とも idle の作業用アカウント（admin / library）\n\nここまで、図書館システムを題材に13章（00〜12）を通しで歩いてきました:\n\n| 章 | テーマ | 学んだこと |\n|---|---|---|\n| 00 | はじめに | RDB と SQL の入口 |\n| 01 | DBとスキーマ作成 | データベースと名前空間（スキーマ） |\n| 02 | テーブル設計DDL | 正規化・制約・IDENTITY |\n| 03 | データ投入 | INSERT・冪等性・CSV |\n| 04 | 検索基本 | WHERE・LIKE・並べ替え |\n| 05 | 結合と集計 | JOIN・GROUP BY |\n| 06 | 更新削除 | UPDATE・DELETE とトランザクション |\n| 07 | ビュー・関数・トリガー | 再利用できる問い合わせと業務ルール |\n| 08 | インデックス性能 | EXPLAIN・索引・100万行 |\n| 09 | トランザクション | 分離レベル・競合・ロック |\n| 10 | ユーザーと権限 | ロール・列・シーケンス・関数・行レベル |\n| 11 | 運用 | バックアップ・監視・移行 |\n| 12 | 総合演習 | 設計から権限まで自分で完成 |\n\nを通しで経験しました。現実のシステムは、この積み上げの組み合わせです。次に自分が作るシステムの設計図に、この道場の作法を持ち帰ってください。`,
      task: 'セッション B を作業用アカウント（admin / library）に接続し直し、最終検収クエリを実行してください（最後の SELECT の結果が採点対象です）。',
      hints: ['「指定の接続に切り替え」で B を admin / library に戻します。', '検収クエリは SELECT current_user ... の後に、count(*) の4列（row_count, constraints, indexes, writer_roles）を返す形です。', '模範解答の列構成（row_count / constraints / indexes / writer_roles）で最後の SELECT を実行します。'],
      solution: `SELECT current_user AS account, current_database() AS database;
SELECT (SELECT count(*) FROM public.reservations)::int AS row_count,
       (SELECT count(*) FROM pg_constraint WHERE conrelid = 'public.reservations'::regclass
         AND contype IN ('p', 'c', 'f'))::int AS constraints,
       (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'reservations')::int AS indexes,
       (SELECT count(*) FROM pg_roles WHERE rolname IN ('lib_app', 'lib_librarian')
         AND has_table_privilege(rolname, 'public.reservations', 'INSERT'))::int AS writer_roles;`,
      replay: '',
      check: { type: 'result-equals', ordered: true, expectedSql: `SELECT (SELECT count(*) FROM public.reservations)::int AS row_count,
       (SELECT count(*) FROM pg_constraint WHERE conrelid = 'public.reservations'::regclass
         AND contype IN ('p', 'c', 'f'))::int AS constraints,
       (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'reservations')::int AS indexes,
       (SELECT count(*) FROM pg_roles WHERE rolname IN ('lib_app', 'lib_librarian')
         AND has_table_privilege(rolname, 'public.reservations', 'INSERT'))::int AS writer_roles LIMIT 1` },
      mysqlNote: 'MySQL での検収も同じ発想です: 表定義は SHOW CREATE TABLE reservations、索引は SHOW INDEX FROM reservations、権限は SHOW GRANTS FOR、行数は SELECT COUNT(*) で確認します。1本のクエリにまとめる文化は PG のカタログの強さ（pg_constraint / pg_indexes / has_table_privilege が全部SQLで引ける）で、MySQL では SHOW 系の命令を組み合わせるのが対応する作法です。お疲れさまでした。' },
  ],
}
export default chapter
