-- Canonical chapter-12 addition.
CREATE TABLE public.reservations (
  reservation_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT reservations_pkey PRIMARY KEY,
  book_id integer CONSTRAINT reservations_book_id_nn NOT NULL,
  member_id integer CONSTRAINT reservations_member_id_nn NOT NULL,
  reserved_at timestamptz DEFAULT CURRENT_TIMESTAMP CONSTRAINT reservations_reserved_at_nn NOT NULL,
  status text DEFAULT 'pending' CONSTRAINT reservations_status_nn NOT NULL,
  CONSTRAINT reservations_status_check CHECK (status IN ('pending', 'fulfilled', 'cancelled')),
  CONSTRAINT reservations_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.books(book_id) ON DELETE RESTRICT,
  CONSTRAINT reservations_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(member_id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX reservations_one_pending_idx ON public.reservations(book_id, member_id) WHERE status = 'pending';
CREATE INDEX reservations_queue_idx ON public.reservations(book_id, reserved_at) WHERE status = 'pending';
