-- Canonical end-of-chapter-2 schema. Do not automatically run at reset.
CREATE TABLE public.categories (
  category_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT categories_pkey PRIMARY KEY,
  name text CONSTRAINT categories_name_nn NOT NULL CONSTRAINT categories_name_key UNIQUE
);
CREATE TABLE public.authors (
  author_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT authors_pkey PRIMARY KEY,
  name text CONSTRAINT authors_name_nn NOT NULL,
  birth_year integer,
  CONSTRAINT authors_birth_year_check CHECK (birth_year BETWEEN 1 AND 2100)
);
CREATE TABLE public.books (
  book_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT books_pkey PRIMARY KEY,
  isbn varchar(13) CONSTRAINT books_isbn_nn NOT NULL CONSTRAINT books_isbn_key UNIQUE,
  title text CONSTRAINT books_title_nn NOT NULL,
  category_id integer CONSTRAINT books_category_id_nn NOT NULL,
  published_year integer,
  price numeric(10,2) DEFAULT 0 CONSTRAINT books_price_nn NOT NULL,
  CONSTRAINT books_year_check CHECK (published_year BETWEEN 1 AND 2100),
  CONSTRAINT books_price_check CHECK (price >= 0),
  CONSTRAINT books_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(category_id) ON DELETE RESTRICT
);
CREATE TABLE public.book_authors (
  book_id integer CONSTRAINT book_authors_book_id_nn NOT NULL,
  author_id integer CONSTRAINT book_authors_author_id_nn NOT NULL,
  CONSTRAINT book_authors_pkey PRIMARY KEY (book_id, author_id),
  CONSTRAINT book_authors_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.books(book_id) ON DELETE CASCADE,
  CONSTRAINT book_authors_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.authors(author_id) ON DELETE RESTRICT
);
CREATE TABLE public.copies (
  copy_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT copies_pkey PRIMARY KEY,
  book_id integer CONSTRAINT copies_book_id_nn NOT NULL,
  barcode text CONSTRAINT copies_barcode_nn NOT NULL CONSTRAINT copies_barcode_key UNIQUE,
  acquired_on date DEFAULT CURRENT_DATE CONSTRAINT copies_acquired_on_nn NOT NULL,
  status text DEFAULT 'available' CONSTRAINT copies_status_nn NOT NULL,
  CONSTRAINT copies_status_check CHECK (status IN ('available', 'loaned', 'repair', 'lost')),
  CONSTRAINT copies_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.books(book_id) ON DELETE RESTRICT
);
CREATE TABLE public.members (
  member_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT members_pkey PRIMARY KEY,
  name text CONSTRAINT members_name_nn NOT NULL,
  email text CONSTRAINT members_email_key UNIQUE,
  joined_on date DEFAULT CURRENT_DATE CONSTRAINT members_joined_on_nn NOT NULL,
  deleted_at timestamptz
);
CREATE TABLE public.loans (
  loan_id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT loans_pkey PRIMARY KEY,
  copy_id integer CONSTRAINT loans_copy_id_nn NOT NULL,
  member_id integer CONSTRAINT loans_member_id_nn NOT NULL,
  loaned_on date DEFAULT CURRENT_DATE CONSTRAINT loans_loaned_on_nn NOT NULL,
  due_on date CONSTRAINT loans_due_on_nn NOT NULL,
  returned_on date,
  CONSTRAINT loans_due_on_check CHECK (due_on >= loaned_on),
  CONSTRAINT loans_returned_on_check CHECK (returned_on IS NULL OR returned_on >= loaned_on),
  CONSTRAINT loans_copy_id_fkey FOREIGN KEY (copy_id) REFERENCES public.copies(copy_id) ON DELETE RESTRICT,
  CONSTRAINT loans_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(member_id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX loans_one_open_copy_idx ON public.loans(copy_id) WHERE returned_on IS NULL;
COMMENT ON TABLE public.books IS '書誌情報。物理的な一冊は copies で管理する';
