-- Temporary test aid: contract end-of-ch9 objects on top of the end-of-ch3 state.
-- Valid only while lessons/ch07-09.ts are unwritten; the real chapters supersede it.
-- Re-running is safe (CREATE OR REPLACE / IF NOT EXISTS / guarded INSERT).

-- ch7: views and materialized view
CREATE OR REPLACE VIEW public.v_book_catalog AS
SELECT b.book_id, b.isbn, b.title, c.name AS category_name
FROM public.books b JOIN public.categories c ON c.category_id = b.category_id;

CREATE OR REPLACE VIEW public.v_overdue_loans AS
SELECT l.loan_id, l.member_id, l.copy_id, l.due_on, (CURRENT_DATE - l.due_on) AS days_overdue
FROM public.loans l
WHERE l.returned_on IS NULL AND l.due_on < CURRENT_DATE;

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_category_stats AS
SELECT c.category_id, COUNT(b.book_id)::bigint AS book_count
FROM public.categories c LEFT JOIN public.books b ON b.category_id = c.category_id
GROUP BY c.category_id;
REFRESH MATERIALIZED VIEW public.mv_category_stats;

-- ch7: late fee function (SECURITY INVOKER by default; unknown loan_id yields NULL)
CREATE OR REPLACE FUNCTION public.calc_late_fee(p_loan_id integer) RETURNS integer
LANGUAGE sql STABLE AS $$
  SELECT GREATEST(COALESCE(l.returned_on, CURRENT_DATE) - l.due_on, 0) * 10
  FROM public.loans l WHERE l.loan_id = p_loan_id
$$;

-- ch7: loan trigger
CREATE OR REPLACE FUNCTION public.check_loan_available() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_status text;
BEGIN
  SELECT status INTO v_status FROM public.copies WHERE copy_id = NEW.copy_id FOR UPDATE;
  IF v_status IS DISTINCT FROM 'available' THEN
    RAISE EXCEPTION '蔵書 % は貸出できません（状態: %）', NEW.copy_id, COALESCE(v_status, '不明')
      USING ERRCODE = '23514';
  END IF;
  UPDATE public.copies SET status = 'loaned' WHERE copy_id = NEW.copy_id;
  RETURN NEW;
END
$$;

CREATE OR REPLACE TRIGGER trg_loans_check_available
BEFORE INSERT ON public.loans
FOR EACH ROW EXECUTE FUNCTION public.check_loan_available();

-- ch7: return procedure
CREATE OR REPLACE PROCEDURE public.return_loan(p_loan_id integer, p_returned_on date DEFAULT CURRENT_DATE)
LANGUAGE plpgsql AS $$
DECLARE
  v_copy_id integer;
BEGIN
  UPDATE public.loans SET returned_on = p_returned_on
  WHERE loan_id = p_loan_id AND returned_on IS NULL
  RETURNING copy_id INTO v_copy_id;
  IF v_copy_id IS NULL THEN
    RAISE EXCEPTION '貸出 % は存在しないか返却済みです', p_loan_id USING ERRCODE = 'P0002';
  END IF;
  UPDATE public.copies SET status = 'available' WHERE copy_id = v_copy_id;
END
$$;

-- ch8: performance table with 1,000,000 rows
CREATE TABLE IF NOT EXISTS public.loan_history (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT loan_history_pkey PRIMARY KEY,
  member_id integer NOT NULL,
  book_id integer NOT NULL,
  loaned_on date NOT NULL,
  returned_on date,
  note text NOT NULL DEFAULT ''
);

INSERT INTO public.loan_history (history_id, member_id, book_id, loaned_on, returned_on, note)
SELECT n, (n - 1) % 20 + 1, (n - 1) % 50 + 1,
  CURRENT_DATE - (n % 730)::integer,
  CASE WHEN n % 10 = 0 THEN NULL ELSE CURRENT_DATE - (n % 730)::integer + 7 END,
  'history ' || n
FROM generate_series(1, 1000000) AS n
WHERE NOT EXISTS (SELECT 1 FROM public.loan_history);

SELECT setval(pg_get_serial_sequence('public.loan_history', 'history_id'), 1000000, true);

CREATE INDEX IF NOT EXISTS loan_history_member_idx ON public.loan_history (member_id);
CREATE INDEX IF NOT EXISTS loan_history_member_date_idx ON public.loan_history (member_id, loaned_on);
CREATE INDEX IF NOT EXISTS loan_history_open_idx ON public.loan_history (loaned_on) WHERE returned_on IS NULL;
CREATE INDEX IF NOT EXISTS books_title_lower_idx ON public.books (lower(title));

ANALYZE public.loan_history;
ANALYZE public.books;

-- ch9 leaves no persistent objects.
